'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { BadgeCheck, Copy, ExternalLink, PauseCircle, RefreshCw, Store } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '@/components/MissionAppShell'
import { supabase } from '@/lib/supabase'
import { MISSION365_REGISTRY_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY } from '@/lib/mission365-public'

const headers={apikey:MISSION365_SUPABASE_PUBLISHABLE_KEY}
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((Number(c)||0)/100)
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function MissionRegistryManager(){
  const [token,setToken]=useState<string|null>(null),[portal,setPortal]=useState<any>(null),[missionId,setMissionId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[onboardingUrl,setOnboardingUrl]=useState('')
  const [vendor,setVendor]=useState({publicName:'',contactEmail:'',websiteUrl:''})
  const [item,setItem]=useState({title:'',description:'',category:'Production',target:'1000',vendorId:'',settlementMode:'vendor_direct',allowPartial:true,dueDate:''})

  const call=useCallback(async(action:string,payload:any={})=>{if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_REGISTRY_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Registry operation failed');return b},[token])
  const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);if(!session){setPortal(null);return}const r=await fetch(MISSION365_REGISTRY_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'portal'})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Registry workspace unavailable');setPortal(b);setMissionId((current:string)=>current&&b.missions?.some((m:any)=>m.id===current)?current:b.missions?.[0]?.id||'')}catch(error){setMessage(error instanceof Error?error.message:'Registry workspace unavailable')}finally{setBusy(false)}},[])
  useEffect(()=>{void load()},[load])

  const selectedMission=useMemo(()=>portal?.missions?.find((m:any)=>m.id===missionId)||null,[portal,missionId])
  const organizationId=selectedMission?.organization_id||''
  const vendors=useMemo(()=>portal?.vendors?.filter((v:any)=>v.organization_id===organizationId)||[],[portal,organizationId])
  const items=useMemo(()=>portal?.items?.filter((i:any)=>i.mission_id===missionId)||[],[portal,missionId])
  const openTotal=items.filter((i:any)=>['open','partially_funded'].includes(i.status)).reduce((n:number,i:any)=>n+Math.max(0,Number(i.target_amount_cents)-Number(i.funded_amount_cents)),0)
  const directReady=vendors.filter((v:any)=>v.onboarding_status==='ready'&&v.transfers_status==='active').length

  async function run(fn:()=>Promise<any>,success:string){setBusy(true);setMessage('');try{const result=await fn();setMessage(success);await load();return result}catch(error){setMessage(error instanceof Error?error.message:'Operation failed')}finally{setBusy(false)}}
  async function saveVendor(e:FormEvent){e.preventDefault();if(!organizationId)return;await run(()=>call('save_vendor',{organizationId,vendor}),'Vendor saved.');setVendor({publicName:'',contactEmail:'',websiteUrl:''})}
  async function startVendor(vendorId:string){setBusy(true);setMessage('');try{const b=await call('start_vendor_onboarding',{organizationId,vendorId});setOnboardingUrl(b.url||'');setMessage('Vendor onboarding link created. Send this secure Stripe link to the vendor.')}catch(error){setMessage(error instanceof Error?error.message:'Could not start vendor onboarding')}finally{setBusy(false)}}
  async function refreshVendor(vendorId:string){await run(()=>call('refresh_vendor',{organizationId,vendorId}),'Vendor payout status refreshed.')}
  async function saveItem(e:FormEvent){e.preventDefault();if(!organizationId||!missionId)return;const targetAmountCents=Math.round(Number(item.target)*100);await run(()=>call('save_item',{organizationId,missionId,item:{title:item.title,description:item.description,category:item.category,targetAmountCents,vendorId:item.settlementMode==='vendor_direct'?item.vendorId:null,settlementMode:item.settlementMode,allowPartial:item.allowPartial,dueDate:item.dueDate||null,sortOrder:items.length}}),'Registry item saved.');setItem({...item,title:'',description:'',target:'1000',dueDate:''})}
  async function publishItem(itemId:string){await run(()=>call('publish_item',{organizationId,itemId}),'Registry item published.')}
  async function pauseItem(itemId:string){await run(()=>call('pause_item',{organizationId,itemId}),'Registry item paused.')}

  if(!token&&!busy)return <MissionAppShell title="Mission Registry" subtitle="Break campaign budgets into exact needs that donors and sponsors can fund directly."><article className="role-card"><h3>Sign in required.</h3><p>Registry setup is restricted to approved mission owners and managers.</p><Link className="button" href="/login">Sign in securely</Link></article></MissionAppShell>

  return <MissionAppShell title="Mission Registry" subtitle="Turn a broad fundraising goal into a transparent shopping list: venue, stage, inventory, equipment, staffing, marketing, and other exact expenses.">
    {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
    <div className="command-bar"><div><p className="eyebrow">CAMPAIGN REGISTRY</p><h2 style={{margin:0}}>{selectedMission?.title||'Choose a mission'}</h2></div><div className="command-actions"><button className="button button-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>{portal?.missions?.length>0&&<select value={missionId} onChange={e=>setMissionId(e.target.value)}>{portal.missions.map((m:any)=><option value={m.id} key={m.id}>{m.title} · {label(m.status)}</option>)}</select>}</div></div>
    <MetricGrid items={[["Registry needs",String(items.length),'Exact campaign expenses listed.'],["Still needed",money(openTotal),'Remaining across open registry items.'],["Vendors ready",String(directReady),`${vendors.length} vendor record(s) total.`]]}/>

    {!selectedMission?<section className="workspace-panel"><h2>Create a mission first.</h2><p>The registry attaches to a specific Mission 365 fundraising campaign.</p><Link className="button" href="/app/mission-owner">Open Mission Builder</Link></section>:<>
      <section className="workspace-panel"><div><p className="eyebrow">1 · APPROVED VENDORS</p><h2>Pay vendors instead of handing over unrestricted cash.</h2><p>Add the vendor, generate a Stripe onboarding link, and have the vendor complete payout verification. Once transfers are active, registry payments can route directly to that vendor.</p></div>
        <form className="application-form" onSubmit={saveVendor}><div className="form-grid"><label>Vendor / supplier name<input value={vendor.publicName} onChange={e=>setVendor({...vendor,publicName:e.target.value})} required/></label><label>Vendor email<input type="email" value={vendor.contactEmail} onChange={e=>setVendor({...vendor,contactEmail:e.target.value})} required/></label><label>Website<input type="url" value={vendor.websiteUrl} onChange={e=>setVendor({...vendor,websiteUrl:e.target.value})} placeholder="https://"/></label></div><button className="button" disabled={busy}>Save vendor</button></form>
        {onboardingUrl&&<article className="ops-card"><div className="ops-title"><div><p className="eyebrow">SECURE VENDOR ONBOARDING LINK</p><h3>Send this link to the vendor.</h3><p className="muted">Stripe collects the vendor's payout and identity information. Mission 365 does not ask you to type their banking details into the app.</p></div><div className="row-actions wrap"><button className="button button-ghost" type="button" onClick={()=>navigator.clipboard.writeText(onboardingUrl)}><Copy size={15}/>Copy link</button><a className="button" href={onboardingUrl} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open link</a></div></div></article>}
        <div className="record-list">{vendors.map((v:any)=><div className="record-row" key={v.id}><div><strong>{v.onboarding_status==='ready'?<BadgeCheck size={15}/>:<Store size={15}/>} {v.public_name}</strong><small>{v.contact_email||'No email'} · {label(v.onboarding_status)} · transfers {label(v.transfers_status)}</small></div><div className="row-actions wrap">{v.onboarding_status!=='ready'?<button className="button button-ghost button-compact" onClick={()=>void startVendor(v.id)}>Create onboarding link</button>:null}<button className="button button-ghost button-compact" onClick={()=>void refreshVendor(v.id)}>Refresh</button></div></div>)}</div>
      </section>

      <section className="workspace-panel"><div><p className="eyebrow">2 · BUILD THE REGISTRY</p><h2>List exactly what the money is for.</h2><p>Examples: stage rental, venue rental, production equipment, food inventory, merchandise inventory, permits, transportation, staffing, security, marketing, or supplies.</p></div>
        <form className="application-form" onSubmit={saveItem}><div className="form-grid"><label>Need / item title<input value={item.title} onChange={e=>setItem({...item,title:e.target.value})} placeholder="Stage + lighting package" required/></label><label>Category<select value={item.category} onChange={e=>setItem({...item,category:e.target.value})}><option>Production</option><option>Venue</option><option>Inventory</option><option>Equipment</option><option>Staffing</option><option>Security</option><option>Transportation</option><option>Marketing</option><option>Permits</option><option>Supplies</option><option>Other</option></select></label><label>Target USD<input type="number" min="1" step="1" value={item.target} onChange={e=>setItem({...item,target:e.target.value})} required/></label><label>Need-by date<input type="date" value={item.dueDate} onChange={e=>setItem({...item,dueDate:e.target.value})}/></label><label>Payment route<select value={item.settlementMode} onChange={e=>setItem({...item,settlementMode:e.target.value})}><option value="vendor_direct">Pay vendor directly</option><option value="mission_payout">Fund mission payout account</option></select></label>{item.settlementMode==='vendor_direct'&&<label>Approved vendor<select value={item.vendorId} onChange={e=>setItem({...item,vendorId:e.target.value})} required><option value="">Choose vendor</option>{vendors.map((v:any)=><option key={v.id} value={v.id}>{v.public_name} · {label(v.onboarding_status)}</option>)}</select></label>}</div><label>Description<textarea value={item.description} onChange={e=>setItem({...item,description:e.target.value})} placeholder="What is being purchased, rented, produced, or paid for?" minLength={5} required/></label><label className="policy-check"><input type="checkbox" checked={item.allowPartial} onChange={e=>setItem({...item,allowPartial:e.target.checked})}/><span>Allow multiple sponsors to split this item. Turn this off when one sponsor should cover the full balance.</span></label><button className="button" disabled={busy}>Save registry item</button></form>
      </section>

      <section className="workspace-panel"><div><p className="eyebrow">3 · LIVE NEEDS</p><h2>Track every line item.</h2></div><div className="registry-grid">{items.map((i:any)=>{const pct=Math.min(100,Math.round(Number(i.funded_amount_cents)/Number(i.target_amount_cents)*100));return <article className="registry-item" key={i.id}><div className="registry-item-top"><div><span className={`status-pill status-${i.status}`}>{label(i.status)}</span><h3>{i.title}</h3><p>{i.description}</p></div><strong>{money(i.target_amount_cents)}</strong></div><div className="registry-progress"><span style={{width:`${pct}%`}}/></div><div className="registry-meta"><span>{money(i.funded_amount_cents)} funded · {pct}%</span><span>{i.settlement_mode==='vendor_direct'?`Direct to ${i.vendor_name||'vendor'}`:'Mission payout'}{i.due_date?` · due ${new Date(`${i.due_date}T00:00:00`).toLocaleDateString()}`:''}</span></div><div className="row-actions wrap">{i.status==='draft'||i.status==='paused'?<button className="button button-compact" onClick={()=>void publishItem(i.id)}>Publish item</button>:null}{['open','partially_funded'].includes(i.status)?<button className="button button-ghost button-compact" onClick={()=>void pauseItem(i.id)}><PauseCircle size={14}/>Pause</button>:null}</div></article>})}{!items.length&&<article className="role-card"><h3>No registry items yet.</h3><p>Add the first exact expense above.</p></article>}</div></section>
    </>}
  </MissionAppShell>
}
