'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Building2, Download, RefreshCw, WalletCards } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '../../../components/MissionAppShell'
import { supabase } from '../../../lib/supabase'
import { MISSION365_BUSINESS_DASHBOARD_URL, MISSION365_OWNER_PORTAL_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY } from '../../../lib/mission365-public'

const headers={'apikey':MISSION365_SUPABASE_PUBLISHABLE_KEY}
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((Number(c)||0)/100)
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export default function BusinessWorkspace(){
 const [data,setData]=useState<any>(null),[token,setToken]=useState<string|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[orgId,setOrgId]=useState(''),[publicMissions,setPublicMissions]=useState<any[]>([])
 const [settings,setSettings]=useState({matched:false,employee:false,matchPercent:'100',perEmployeeLimit:'0',monthlyBudget:'0',status:'draft'})
 const [sponsor,setSponsor]=useState({missionId:'',amount:'5000',type:'direct'})
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);if(!session){setData(null);return}const [r,missions]=await Promise.all([fetch(MISSION365_BUSINESS_DASHBOARD_URL,{headers:{...headers,Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),supabase.from('mission365_missions').select('id,slug,title,category,status,goal_amount_cents,funded_amount_cents').in('status',['published','funded','reporting']).order('published_at',{ascending:false})]);const b=await r.json();if(!r.ok)throw new Error(b.error||'Business dashboard unavailable');setData(b);setPublicMissions(missions.data||[]);const first=b.organizations?.[0]?.id||'';setOrgId((current:string)=>current&&b.organizations?.some((o:any)=>o.id===current)?current:first)}catch(error){setMessage(error instanceof Error?error.message:'Business dashboard unavailable')}finally{setBusy(false)}},[])
 useEffect(()=>{void load()},[load])
 const org=useMemo(()=>data?.organizations?.find((o:any)=>o.id===orgId)||null,[data,orgId]);const currentSettings=data?.settings?.find((s:any)=>s.organization_id===orgId)||null;useEffect(()=>{if(currentSettings)setSettings({matched:currentSettings.matched_giving_enabled,employee:currentSettings.employee_giving_enabled,matchPercent:String(currentSettings.match_percent),perEmployeeLimit:String(Number(currentSettings.per_employee_limit_cents)/100),monthlyBudget:String(Number(currentSettings.monthly_budget_cents)/100),status:currentSettings.status})},[currentSettings])
 async function post(action:string,payload:any={}){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_BUSINESS_DASHBOARD_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Operation failed');return b}
 async function run(fn:()=>Promise<any>,success:string,refresh=true){setBusy(true);setMessage('');try{await fn();setMessage(success);if(refresh)await load()}catch(error){setMessage(error instanceof Error?error.message:'Operation failed')}finally{setBusy(false)}}
 async function initialize(applicationId:string){if(!token)return;await run(async()=>{const r=await fetch(MISSION365_OWNER_PORTAL_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'initialize_workspace',applicationId})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Could not create business workspace')},'Business verification workspace created.')}
 async function saveSettings(e:FormEvent){e.preventDefault();await run(()=>post('update_settings',{organizationId:orgId,matchedGivingEnabled:settings.matched,employeeGivingEnabled:settings.employee,matchPercent:Number(settings.matchPercent),perEmployeeLimit:Number(settings.perEmployeeLimit),monthlyBudget:Number(settings.monthlyBudget),status:settings.status}),'Business giving settings saved.')}
 async function createSponsor(e:FormEvent){e.preventDefault();await run(()=>post('create_sponsorship',{organizationId:orgId,missionId:sponsor.missionId,commitmentAmount:Number(sponsor.amount),sponsorshipType:sponsor.type}),'Sponsorship commitment created.')}
 function downloadCsv(filename:string,csv:string){const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
 if(!token&&!busy)return <MissionAppShell title="Business Impact Dashboard" subtitle="Verified sponsorships, employee giving, matching rules, and accountable impact reporting."><article className="role-card"><h3>Business sign-in required.</h3><Link className="button" href="/login">Sign in securely</Link></article></MissionAppShell>
 if(!org)return <MissionAppShell title="Business Impact Dashboard" subtitle="Create a verified business workspace before sponsoring missions.">{message&&<article className="role-card"><strong>{message}</strong></article>}{data?.applications?.length?data.applications.map((a:any)=><article className="role-card" key={a.id}><p className="eyebrow">{label(a.status)}</p><h3>{a.public_name}</h3><button className="button" onClick={()=>void initialize(a.id)}>Create / open business workspace</button></article>):<article className="role-card"><Building2/><h3>No business-partner application yet.</h3><Link className="button" href="/apply?role=business">Apply as a business partner</Link></article>}</MissionAppShell>
 return <MissionAppShell title="Business Impact Dashboard" subtitle="Sponsorship commitments, funded impact, employee/matched giving settings, and exportable reporting.">
  <div className="command-bar"><div><p className="eyebrow">{org.public_name}</p><p>{label(org.verification_status)}</p></div><div className="command-actions">{data.organizations.length>1&&<select value={orgId} onChange={e=>setOrgId(e.target.value)}>{data.organizations.map((o:any)=><option key={o.id} value={o.id}>{o.public_name}</option>)}</select>}<button className="button button-ghost" onClick={()=>void run(async()=>{const b=await post('export_report');downloadCsv(b.filename,b.csv)},'Business impact export downloaded.',false)}><Download size={16}/>Export impact</button><button className="button button-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button></div></div>
  {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
  <MetricGrid items={[["Contributed",data?money(data.metrics.contributedCents):'—','Actual sponsorship funding after recorded refunds.'],["Committed",data?money(data.metrics.committedCents):'—','Total sponsorship commitments.'],["Active sponsorships",data?String(data.metrics.activeSponsorships):'—','Currently active business sponsorships.'],["Giving programs",data?String(data.metrics.givingPrograms):'—','Active matched or employee-giving programs.']]}/>

  <section className="workspace-panel"><div><p className="eyebrow">BUSINESS VERIFICATION & TERMS</p><h2>Verified businesses can fund sponsorships.</h2><p>Use the verification workspace for organization evidence and payout setup. Business sponsorship terms must be accepted before a commitment is created.</p></div><div className="row-actions wrap"><Link className="button button-ghost" href="/app/mission-owner">Open verification & payout setup</Link><Link className="button button-ghost" href="/legal#business">Review business sponsor terms</Link><button className="button" onClick={()=>void run(()=>post('accept_terms'),'Business sponsor terms accepted.')}>Accept current business terms</button></div></section>

  <section className="workspace-panel"><div><p className="eyebrow">EMPLOYEE & MATCHED GIVING</p><h2>Set business-level participation rules.</h2></div><form className="application-form" onSubmit={saveSettings}><div className="preference-grid"><label><input type="checkbox" checked={settings.matched} onChange={e=>setSettings({...settings,matched:e.target.checked})}/> Employer matching</label><label><input type="checkbox" checked={settings.employee} onChange={e=>setSettings({...settings,employee:e.target.checked})}/> Employee giving</label></div><div className="form-grid"><label>Match percentage<input type="number" min="0" max="500" value={settings.matchPercent} onChange={e=>setSettings({...settings,matchPercent:e.target.value})}/></label><label>Per-employee limit USD<input type="number" min="0" value={settings.perEmployeeLimit} onChange={e=>setSettings({...settings,perEmployeeLimit:e.target.value})}/></label><label>Monthly business budget USD<input type="number" min="0" value={settings.monthlyBudget} onChange={e=>setSettings({...settings,monthlyBudget:e.target.value})}/></label><label>Program status<select value={settings.status} onChange={e=>setSettings({...settings,status:e.target.value})}><option value="draft">Draft</option><option value="active">Active</option><option value="paused">Paused</option></select></label></div><button className="button">Save giving program</button></form></section>

  <section className="workspace-panel"><div><p className="eyebrow">NEW SPONSORSHIP</p><h2>Commit to a verified public mission.</h2></div><form className="application-form" onSubmit={createSponsor}><label>Mission<select required value={sponsor.missionId} onChange={e=>setSponsor({...sponsor,missionId:e.target.value})}><option value="">Choose a verified mission</option>{publicMissions.map(m=><option value={m.id} key={m.id}>{m.title} · {money(m.funded_amount_cents)} / {money(m.goal_amount_cents)}</option>)}</select></label><div className="form-grid"><label>Commitment USD<input type="number" min="1" value={sponsor.amount} onChange={e=>setSponsor({...sponsor,amount:e.target.value})}/></label><label>Sponsorship type<select value={sponsor.type} onChange={e=>setSponsor({...sponsor,type:e.target.value})}><option value="direct">Direct sponsorship</option><option value="matched_giving">Matched giving</option><option value="employee_giving">Employee giving</option><option value="campaign">Campaign</option></select></label></div><button className="button" disabled={org.verification_status!=='verified'}>Create sponsorship commitment</button></form>{org.verification_status!=='verified'&&<p className="muted">Funding stays locked until the business organization is verified.</p>}</section>

  <section className="workspace-panel"><div><p className="eyebrow"><WalletCards size={14}/> SPONSORSHIP PORTFOLIO</p><h2>Committed versus funded.</h2></div>{!data?.sponsorships?.length?<p>No sponsorships recorded yet.</p>:<div className="record-list">{data.sponsorships.map((s:any)=><div className="record-row" key={s.id}><div><strong>{s.mission?.title||'Mission sponsorship'}</strong><small>{label(s.sponsorship_type)} · {label(s.status)} · {money(s.funded_amount_cents)} funded of {money(s.commitment_amount_cents)}</small></div><div className="row-actions">{['active','draft'].includes(s.status)&&Number(s.funded_amount_cents)<Number(s.commitment_amount_cents)&&<button className="button button-compact" onClick={()=>void run(async()=>{const remaining=(Number(s.commitment_amount_cents)-Number(s.funded_amount_cents))/100;const entered=window.prompt('Amount to fund now (USD)',String(remaining));if(!entered)return;const b=await post('fund_sponsorship',{sponsorshipId:s.id,amount:Number(entered)});window.location.assign(b.checkoutUrl)},'Opening secure sponsorship checkout…',false)}>Fund</button>}{!['fulfilled','cancelled'].includes(s.status)&&<button className="button button-ghost button-compact" onClick={()=>void run(()=>post('cancel_sponsorship',{sponsorshipId:s.id}),'Sponsorship cancelled.')}>Cancel</button>}</div></div>)}</div>}</section>
 </MissionAppShell>
}
