import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'cache-control':'no-store'}})
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function db(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function scoped(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
async function stripeSecret(admin:any){let key=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!key){const {data}=await admin.rpc('mission365_get_runtime_secret',{secret_name:'stripe_api_key'});key=String(data||'')}return key}
async function userFor(req:Request){const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return {error:json({error:'Authentication required'},401)};const {data:{user},error}=await scoped(auth).auth.getUser(token);if(error||!user)return {error:json({error:'Invalid session'},401)};return {user}}
async function memberRole(admin:any,userId:string,organizationId:string){const {data}=await admin.from('mission365_organization_members').select('member_role').eq('user_id',userId).eq('organization_id',organizationId).maybeSingle();return String(data?.member_role||'')}
async function snapshot(admin:any,userId:string){
 const [{data:memberships},{data:applications}]=await Promise.all([
  admin.from('mission365_organization_members').select('organization_id,member_role,created_at').eq('user_id',userId),
  admin.from('mission365_applications').select('id,organization_id,public_name,status,created_at').eq('applicant_user_id',userId).eq('application_type','business_partner').order('created_at',{ascending:false})
 ]);
 const memberOrgIds=(memberships||[]).map((m:any)=>m.organization_id);
 const organizations=memberOrgIds.length?(await admin.from('mission365_organizations').select('*').in('id',memberOrgIds).eq('organization_type','business')).data||[]:[];
 const businessIds=organizations.map((o:any)=>o.id);
 const sponsorships=businessIds.length?(await admin.from('mission365_business_sponsorships').select('*').in('business_organization_id',businessIds).order('created_at',{ascending:false})).data||[]:[];
 const settings=businessIds.length?(await admin.from('mission365_business_giving_settings').select('*').in('organization_id',businessIds)).data||[]:[];
 const missionIds=Array.from(new Set(sponsorships.map((s:any)=>s.mission_id))) as string[];
 const missions=missionIds.length?(await admin.from('mission365_missions').select('id,slug,title,summary,category,status,funded_amount_cents,goal_amount_cents,published_at').in('id',missionIds)).data||[]:[];
 const missionMap=new Map(missions.map((m:any)=>[m.id,m]));
 const enriched=sponsorships.map((s:any)=>({...s,mission:missionMap.get(s.mission_id)||null}));
 return {metrics:{contributedCents:sponsorships.reduce((n:number,s:any)=>n+Number(s.funded_amount_cents||0),0),committedCents:sponsorships.reduce((n:number,s:any)=>n+Number(s.commitment_amount_cents||0),0),activeSponsorships:sponsorships.filter((s:any)=>s.status==='active').length,givingPrograms:settings.filter((s:any)=>s.status==='active'&&(s.matched_giving_enabled||s.employee_giving_enabled)).length},organizations,applications:applications||[],sponsorships:enriched,settings,memberships:memberships||[]}
}
Deno.serve(async(req:Request)=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!['GET','POST'].includes(req.method))return json({error:'Method not allowed'},405)
 try{
  const auth=await userFor(req);if('error' in auth)return auth.error;const user=auth.user!;const admin=db();if(req.method==='GET')return json(await snapshot(admin,user.id));
  const body=await req.json();const action=String(body?.action||'')
  if(action==='accept_terms'){await admin.from('mission365_terms_acceptances').upsert({user_id:user.id,document_key:'business_terms',version:'2026-08-08',metadata:{surface:'business_dashboard'}},{onConflict:'user_id,document_key,version',ignoreDuplicates:true});return json({accepted:true,version:'2026-08-08'})}
  if(action==='update_settings'){
   const organizationId=String(body.organizationId||'');const role=await memberRole(admin,user.id,organizationId);if(!['owner','manager'].includes(role))return json({error:'Business owner or manager access required'},403)
   const {data:org}=await admin.from('mission365_organizations').select('organization_type').eq('id',organizationId).maybeSingle();if(org?.organization_type!=='business')return json({error:'Business organization required'},409)
   const matchPercent=Number(body.matchPercent??100),perEmployeeLimitCents=Math.round(Number(body.perEmployeeLimit||0)*100),monthlyBudgetCents=Math.round(Number(body.monthlyBudget||0)*100),status=String(body.status||'draft');if(!['draft','active','paused'].includes(status)||!Number.isFinite(matchPercent)||matchPercent<0||matchPercent>500||!Number.isFinite(perEmployeeLimitCents)||perEmployeeLimitCents<0||!Number.isFinite(monthlyBudgetCents)||monthlyBudgetCents<0)return json({error:'Invalid giving-program settings'},400)
   const {data,error}=await admin.from('mission365_business_giving_settings').upsert({organization_id:organizationId,matched_giving_enabled:body.matchedGivingEnabled===true,employee_giving_enabled:body.employeeGivingEnabled===true,match_percent:matchPercent,per_employee_limit_cents:perEmployeeLimitCents,monthly_budget_cents:monthlyBudgetCents,status,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'organization_id'}).select('*').single();if(error)throw error;return json({settings:data})
  }
  if(action==='create_sponsorship'){
   const organizationId=String(body.organizationId||''),missionId=String(body.missionId||'');const role=await memberRole(admin,user.id,organizationId);if(!['owner','manager'].includes(role))return json({error:'Business owner or manager access required'},403)
   const [{data:org},{data:mission},{data:terms}]=await Promise.all([admin.from('mission365_organizations').select('organization_type,verification_status').eq('id',organizationId).maybeSingle(),admin.from('mission365_missions').select('id,status,published_at').eq('id',missionId).maybeSingle(),admin.from('mission365_terms_acceptances').select('id').eq('user_id',user.id).eq('document_key','business_terms').eq('version','2026-08-08').maybeSingle()]);if(org?.organization_type!=='business')return json({error:'Business organization required'},409);if(!terms)return json({error:'Accept the current business sponsor terms first.'},428);if(!mission||!['published','funded','reporting'].includes(mission.status)||!mission.published_at)return json({error:'Only published missions can be sponsored.'},409)
   const amountCents=Math.round(Number(body.commitmentAmount||0)*100),type=String(body.sponsorshipType||'direct');if(!Number.isFinite(amountCents)||amountCents<100||!['direct','matched_giving','employee_giving','campaign'].includes(type))return json({error:'Valid sponsorship amount and type are required.'},400);const status=org.verification_status==='verified'?'active':'draft';const {data,error}=await admin.from('mission365_business_sponsorships').insert({business_organization_id:organizationId,mission_id:missionId,commitment_amount_cents:amountCents,funded_amount_cents:0,sponsorship_type:type,status,starts_at:status==='active'?new Date().toISOString():null}).select('*').single();if(error)throw error;await admin.from('mission365_audit_log').insert({actor_user_id:user.id,action:'business.sponsorship.created',entity_type:'business_sponsorship',entity_id:data.id,after_state:{status,commitment_amount_cents:amountCents},metadata:{business_organization_id:organizationId,mission_id:missionId}});return json({sponsorship:data})
  }
  if(action==='cancel_sponsorship'){
   const sponsorshipId=String(body.sponsorshipId||'');const {data:s}=await admin.from('mission365_business_sponsorships').select('*').eq('id',sponsorshipId).maybeSingle();if(!s)return json({error:'Sponsorship not found'},404);const role=await memberRole(admin,user.id,s.business_organization_id);if(!['owner','manager'].includes(role))return json({error:'Business owner or manager access required'},403);const {data:updated,error}=await admin.from('mission365_business_sponsorships').update({status:'cancelled',updated_at:new Date().toISOString()}).eq('id',sponsorshipId).select('*').single();if(error)throw error;return json({sponsorship:updated})
  }
  if(action==='fund_sponsorship'){
   const sponsorshipId=String(body.sponsorshipId||'');const {data:s}=await admin.from('mission365_business_sponsorships').select('*').eq('id',sponsorshipId).maybeSingle();if(!s)return json({error:'Sponsorship not found'},404);if(s.status==='cancelled'||s.status==='fulfilled')return json({error:'This sponsorship is not open for additional funding.'},409)
   const role=await memberRole(admin,user.id,s.business_organization_id);if(!['owner','manager'].includes(role))return json({error:'Business owner or manager access required'},403)
   const [{data:org},{data:mission}]=await Promise.all([admin.from('mission365_organizations').select('verification_status').eq('id',s.business_organization_id).maybeSingle(),admin.from('mission365_missions').select('title,status,published_at,organization_id').eq('id',s.mission_id).maybeSingle()]);if(org?.verification_status!=='verified')return json({error:'Business verification is required before funding sponsorships.'},409);if(!mission||!['published','funded','reporting'].includes(mission.status)||!mission.published_at)return json({error:'Mission is not open for funding.'},409)
   const {data:recipientPayout}=await admin.from('mission365_payout_accounts').select('onboarding_status,transfers_status').eq('organization_id',mission.organization_id).maybeSingle();if(!recipientPayout||recipientPayout.onboarding_status!=='ready'||recipientPayout.transfers_status!=='active')return json({error:'Mission owner payout onboarding is not ready.'},409)
   const {count:risks}=await admin.from('mission365_risk_events').select('id',{count:'exact',head:true}).eq('status','open').in('severity',['high','critical']).or(`mission_id.eq.${s.mission_id},organization_id.eq.${mission.organization_id}`);if(risks)return json({error:'Funding is paused while a high-severity risk review is open.'},423)
   const remaining=Math.max(0,Number(s.commitment_amount_cents)-Number(s.funded_amount_cents));const amountCents=Math.round(Number(body.amount||remaining/100)*100);if(!Number.isFinite(amountCents)||amountCents<100||amountCents>remaining)return json({error:'Funding amount must be between $1 and the remaining sponsorship commitment.',remainingCents:remaining},400)
   const key=await stripeSecret(admin);if(!key||key.startsWith('REPLACE_WITH_'))return json({error:'Business funding is credential-gated until Stripe is activated.'},503)
   const givingPlanId=crypto.randomUUID(),donationId=crypto.randomUUID(),idempotencyKey=crypto.randomUUID(),fee=Math.floor(amountCents*500/10000);
   await admin.from('mission365_user_roles').upsert({user_id:user.id,role:'donor_business',status:'active',updated_at:new Date().toISOString()},{onConflict:'user_id,role'});
   await admin.from('mission365_giving_plans').insert({id:givingPlanId,donor_user_id:user.id,mission_id:s.mission_id,amount_cents:amountCents,cadence:'one_time',status:'pending',donor_type:'business',business_organization_id:s.business_organization_id});
   await admin.from('mission365_donations').insert({id:donationId,giving_plan_id:givingPlanId,donor_user_id:user.id,mission_id:s.mission_id,business_organization_id:s.business_organization_id,sponsorship_id:s.id,donor_type:'business',amount_cents:amountCents,platform_fee_cents:fee,refunded_amount_cents:0,currency:'usd',status:'pending',idempotency_key:idempotencyKey})
   const metadata={mission_id:s.mission_id,donor_user_id:user.id,giving_plan_id:givingPlanId,donation_id:donationId,sponsorship_id:s.id,business_organization_id:s.business_organization_id,donor_type:'business'};
   const params=new URLSearchParams();params.set('mode','payment');params.set('success_url','https://mission-365.vercel.app/app/business?checkout=success&session_id={CHECKOUT_SESSION_ID}');params.set('cancel_url','https://mission-365.vercel.app/app/business?checkout=cancelled');if(user.email)params.set('customer_email',user.email);params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]','usd');params.set('line_items[0][price_data][unit_amount]',String(amountCents));params.set('line_items[0][price_data][product_data][name]',`Mission 365 Business Sponsorship — ${mission.title}`);for(const [k,v] of Object.entries(metadata))params.set(`metadata[${k}]`,String(v));for(const [k,v] of Object.entries(metadata))params.set(`payment_intent_data[metadata][${k}]`,String(v));params.set('integration_identifier','mission365_business_qwertyui')
   const response=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.dahlia','Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`m365-sponsor-${idempotencyKey}`},body:params.toString()});const session=await response.json();if(!response.ok){await admin.from('mission365_donations').update({status:'failed'}).eq('id',donationId);await admin.from('mission365_giving_plans').update({status:'cancelled'}).eq('id',givingPlanId);throw new Error(session?.error?.message||'Sponsorship checkout failed')}await admin.from('mission365_giving_plans').update({stripe_checkout_session_id:session.id}).eq('id',givingPlanId);await admin.from('mission365_donations').update({stripe_checkout_session_id:session.id}).eq('id',donationId);return json({checkoutUrl:session.url,sessionId:session.id})
  }
  if(action==='export_report'){const data=await snapshot(admin,user.id);const header='Business Organization,Mission,Type,Status,Committed USD,Funded USD';const rows=data.sponsorships.map((s:any)=>[s.business_organization_id,s.mission?.title||s.mission_id,s.sponsorship_type,s.status,(Number(s.commitment_amount_cents)/100).toFixed(2),(Number(s.funded_amount_cents)/100).toFixed(2)].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));return json({filename:`mission365-business-impact-${new Date().toISOString().slice(0,10)}.csv`,csv:[header,...rows].join('\n')})}
  return json({error:'Unsupported action'},400)
 }catch(error){console.error('mission365 business dashboard failed',error);return json({error:error instanceof Error?error.message:'Dashboard unavailable'},500)}
})
