import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'cache-control':'no-store'}})
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function scoped(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
async function adminRole(db:any,user:any){const meta=String(user.app_metadata?.mission365_role||'');if(['admin','finance'].includes(meta))return meta;if(user.email_confirmed_at&&user.email){const {data}=await db.from('mission365_reviewer_access').select('role').eq('email',user.email.toLowerCase()).eq('active',true).maybeSingle();if(['admin','finance'].includes(String(data?.role||'')))return String(data.role)}return ''}
async function sendEmail(to:string,title:string,body:string){const key=Deno.env.get('RESEND_API_KEY')||'';const from=Deno.env.get('MISSION365_FROM_EMAIL')||'';if(!key||!from)return {configured:false};const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from,to:[to],subject:title,text:body})});const data=await response.json();if(!response.ok)throw new Error(data?.message||'Email provider rejected message');return {configured:true,id:data.id||null}}
async function sendSms(to:string,body:string){const sid=Deno.env.get('TWILIO_ACCOUNT_SID')||'',token=Deno.env.get('TWILIO_AUTH_TOKEN')||'',from=Deno.env.get('MISSION365_SMS_FROM')||'';if(!sid||!token||!from)return {configured:false};const params=new URLSearchParams({To:to,From:from,Body:body});const auth=btoa(`${sid}:${token}`);const response=await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}/Messages.json`,{method:'POST',headers:{Authorization:`Basic ${auth}`,'Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});const data=await response.json();if(!response.ok)throw new Error(data?.message||'SMS provider rejected message');return {configured:true,id:data.sid||null}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';const {data:{user},error}=await scoped(auth).auth.getUser(token);if(error||!user)return json({error:'Authentication required'},401);const db=admin();if(!await adminRole(db,user))return json({error:'Admin or finance authorization required'},403);const {data:rows}=await db.from('mission365_notification_deliveries').select('id,notification_id,channel,status,mission365_notifications!inner(user_id,title,body)').eq('status','queued').in('channel',['email','sms']).order('created_at',{ascending:true}).limit(50);let sent=0,failed=0,unconfigured=0;for(const row of rows||[]){const n:any=(row as any).mission365_notifications;const {data:{user:recipient}}=await db.auth.admin.getUserById(n.user_id);try{if(row.channel==='email'){if(!recipient?.email){await db.from('mission365_notification_deliveries').update({status:'failed',error_message:'Recipient has no email',attempted_at:new Date().toISOString()}).eq('id',row.id);failed++;continue}const result=await sendEmail(recipient.email,n.title,n.body);if(!result.configured){unconfigured++;continue}await db.from('mission365_notification_deliveries').update({status:'sent',provider_message_id:result.id,attempted_at:new Date().toISOString(),error_message:null}).eq('id',row.id);sent++}else{if(!recipient?.phone){await db.from('mission365_notification_deliveries').update({status:'failed',error_message:'Recipient has no verified phone',attempted_at:new Date().toISOString()}).eq('id',row.id);failed++;continue}const result=await sendSms(recipient.phone,n.body);if(!result.configured){unconfigured++;continue}await db.from('mission365_notification_deliveries').update({status:'sent',provider_message_id:result.id,attempted_at:new Date().toISOString(),error_message:null}).eq('id',row.id);sent++}}catch(err){await db.from('mission365_notification_deliveries').update({status:'failed',error_message:err instanceof Error?err.message:'Provider failure',attempted_at:new Date().toISOString()}).eq('id',row.id);failed++}}return json({processed:(rows||[]).length,sent,failed,unconfigured,providers:{email:Boolean(Deno.env.get('RESEND_API_KEY')&&Deno.env.get('MISSION365_FROM_EMAIL')),sms:Boolean(Deno.env.get('TWILIO_ACCOUNT_SID')&&Deno.env.get('TWILIO_AUTH_TOKEN')&&Deno.env.get('MISSION365_SMS_FROM'))}})}catch(error){console.error('mission365 notification dispatch failed',error);return json({error:error instanceof Error?error.message:'Dispatch failed'},500)}})
