import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const corsHeaders={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function adminClient(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function userClient(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
async function stripeSecret(admin:any){let key=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!key){const {data}=await admin.rpc('mission365_get_runtime_secret',{secret_name:'stripe_api_key'});key=String(data||'')}return key}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return Response.json({error:'Method not allowed'},{status:405,headers:corsHeaders});let givingPlanId='',donationId='';try{
 const auth=req.headers.get('authorization')||'',token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return Response.json({error:'Authentication required'},{status:401,headers:corsHeaders});const {data:{user},error:userError}=await userClient(auth).auth.getUser(token);if(userError||!user)return Response.json({error:'Invalid session'},{status:401,headers:corsHeaders});
 const body=await req.json();const missionId=String(body?.missionId||''),amountCents=Number(body?.amountCents),requestedCadence=String(body?.cadence||'monthly'),cadence='monthly',donorType=String(body?.donorType||'personal'),businessOrganizationId=body?.businessOrganizationId?String(body.businessOrganizationId):null;
 if(requestedCadence!=='monthly')return Response.json({error:'Mission 365 giving is monthly subscription-only.'},{status:400,headers:corsHeaders});
 if(!missionId||!Number.isInteger(amountCents))return Response.json({error:'A valid mission and monthly amount are required'},{status:400,headers:corsHeaders});if(!['personal','business'].includes(donorType))return Response.json({error:'Choose personal or business giving'},{status:400,headers:corsHeaders});
 if(donorType==='personal'&&amountCents<500)return Response.json({error:'Personal monthly giving starts at $5.'},{status:400,headers:corsHeaders});if(donorType==='business'&&amountCents<2500)return Response.json({error:'Business monthly giving starts at $25.'},{status:400,headers:corsHeaders});
 const admin=adminClient();if(donorType==='business'){
  if(!businessOrganizationId)return Response.json({error:'Choose a business donor profile before starting business giving.'},{status:400,headers:corsHeaders});
  const [{data:membership},{data:business}]=await Promise.all([admin.from('mission365_organization_members').select('member_role').eq('organization_id',businessOrganizationId).eq('user_id',user.id).maybeSingle(),admin.from('mission365_organizations').select('id,public_name,organization_type').eq('id',businessOrganizationId).maybeSingle()]);
  if(!membership||business?.organization_type!=='business')return Response.json({error:'You do not have access to that business donor profile.'},{status:403,headers:corsHeaders});
 }
 const {data:rateOk,error:rateError}=await admin.rpc('mission365_consume_rate_limit',{p_bucket:'checkout',p_subject:user.id,p_limit:12,p_window_seconds:3600});if(rateError)throw rateError;if(!rateOk)return Response.json({error:'Too many checkout attempts. Please try again later.'},{status:429,headers:corsHeaders});
 const {data:terms}=await admin.from('mission365_terms_acceptances').select('id').eq('user_id',user.id).eq('document_key','donor_terms').eq('version','2026-08-08').maybeSingle();if(!terms)return Response.json({error:'Please accept the current Mission 365 donor terms before giving.'},{status:428,headers:corsHeaders});
 const {data:mission,error:missionError}=await admin.from('mission365_missions').select('id,title,status,published_at,organization_id').eq('id',missionId).single();if(missionError||!mission||!['published','funded','reporting'].includes(mission.status)||!mission.published_at)return Response.json({error:'This mission is not currently open for verified giving'},{status:409,headers:corsHeaders});
 const [{data:org},{data:payout},{count:riskCount}]=await Promise.all([admin.from('mission365_organizations').select('verification_status').eq('id',mission.organization_id).maybeSingle(),admin.from('mission365_payout_accounts').select('onboarding_status,transfers_status').eq('organization_id',mission.organization_id).maybeSingle(),admin.from('mission365_risk_events').select('id',{count:'exact',head:true}).eq('mission_id',missionId).eq('status','open').in('severity',['high','critical'])]);if(org?.verification_status!=='verified'||payout?.onboarding_status!=='ready'||payout?.transfers_status!=='active')return Response.json({error:'Giving is paused until the mission owner remains verified and payout-ready.'},{status:409,headers:corsHeaders});if(riskCount)return Response.json({error:'Giving is temporarily paused while a risk review is open.'},{status:423,headers:corsHeaders});
 const key=await stripeSecret(admin);if(!key||key.startsWith('REPLACE_WITH_'))return Response.json({error:'Mission 365 giving is not activated yet'},{status:503,headers:corsHeaders});
 givingPlanId=crypto.randomUUID();donationId=crypto.randomUUID();const idempotencyKey=crypto.randomUUID(),platformFeeCents=Math.floor(amountCents*500/10000);const role=donorType==='business'?'donor_business':'donor_personal';await admin.from('mission365_user_roles').upsert({user_id:user.id,role,status:'active',updated_at:new Date().toISOString()},{onConflict:'user_id,role'});
 const {error:planError}=await admin.from('mission365_giving_plans').insert({id:givingPlanId,donor_user_id:user.id,mission_id:missionId,amount_cents:amountCents,cadence,status:'pending',donor_type:donorType,business_organization_id:businessOrganizationId});if(planError)throw planError;
 const {error:donationError}=await admin.from('mission365_donations').insert({id:donationId,giving_plan_id:givingPlanId,donor_user_id:user.id,mission_id:missionId,business_organization_id:businessOrganizationId,donor_type:donorType,amount_cents:amountCents,platform_fee_cents:platformFeeCents,refunded_amount_cents:0,currency:'usd',status:'pending',idempotency_key:idempotencyKey});if(donationError)throw donationError;
 const {data:priorCustomer}=await admin.from('mission365_giving_plans').select('stripe_customer_id').eq('donor_user_id',user.id).not('stripe_customer_id','is',null).order('created_at',{ascending:false}).limit(1).maybeSingle();
 const params=new URLSearchParams();params.set('mode','subscription');params.set('success_url',donorType==='business'?'https://mission-365.vercel.app/app/business?checkout=success&session_id={CHECKOUT_SESSION_ID}':'https://mission-365.vercel.app/app/donor?checkout=success&session_id={CHECKOUT_SESSION_ID}');params.set('cancel_url',`https://mission-365.vercel.app/missions?checkout=cancelled`);if(priorCustomer?.stripe_customer_id)params.set('customer',priorCustomer.stripe_customer_id);else if(user.email)params.set('customer_email',user.email);params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]','usd');params.set('line_items[0][price_data][unit_amount]',String(amountCents));params.set('line_items[0][price_data][product_data][name]',`Mission 365 ${donorType==='business'?'Business ':''}Monthly Support — ${mission.title}`);params.set('line_items[0][price_data][recurring][interval]','month');
 const metadata:any={mission_id:missionId,donor_user_id:user.id,giving_plan_id:givingPlanId,donation_id:donationId,donor_type:donorType};if(businessOrganizationId)metadata.business_organization_id=businessOrganizationId;for(const [k,v] of Object.entries(metadata))params.set(`metadata[${k}]`,String(v));params.set('integration_identifier','mission365_giving_qrstuvwx');
 for(const [k,v] of Object.entries(metadata))if(k!=='donation_id')params.set(`subscription_data[metadata][${k}]`,String(v));
 const stripeResponse=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.dahlia','Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':`mission365-checkout-${idempotencyKey}`},body:params.toString()});const session=await stripeResponse.json();if(!stripeResponse.ok)throw new Error(session?.error?.message||'Stripe subscription checkout creation failed');await Promise.all([admin.from('mission365_giving_plans').update({stripe_checkout_session_id:session.id,stripe_customer_id:typeof session.customer==='string'?session.customer:null}).eq('id',givingPlanId),admin.from('mission365_donations').update({stripe_checkout_session_id:session.id}).eq('id',donationId)]);return Response.json({checkoutUrl:session.url,sessionId:session.id,mode:'subscription',cadence:'monthly'},{headers:corsHeaders})
 }catch(error){const admin=adminClient();if(donationId)await admin.from('mission365_donations').update({status:'failed'}).eq('id',donationId).eq('status','pending');if(givingPlanId)await admin.from('mission365_giving_plans').update({status:'cancelled'}).eq('id',givingPlanId).eq('status','pending');console.error('mission365 checkout failed',error);return Response.json({error:error instanceof Error?error.message:'Checkout failed'},{status:500,headers:corsHeaders})}})
