import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, OPTIONS'}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'cache-control':'no-store'}})
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function scoped(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
async function reviewerRole(db:any,user:any){const meta=String(user.app_metadata?.mission365_role||'');if(['admin','reviewer','finance'].includes(meta))return meta;if(user.email_confirmed_at&&user.email){const {data}=await db.from('mission365_reviewer_access').select('role').eq('email',user.email.toLowerCase()).eq('active',true).maybeSingle();if(['admin','reviewer','finance'].includes(String(data?.role||'')))return String(data.role)}return ''}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='GET')return json({error:'Method not allowed'},405);try{const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';const {data:{user},error}=await scoped(auth).auth.getUser(token);if(error||!user)return json({error:'Authentication required'},401);const db=admin();const role=await reviewerRole(db,user);if(!role)return json({error:'Reviewer authorization required'},403)
const [{data:orgs},{data:applications},{data:missions},{data:updates},{data:milestones},{data:payouts},{data:risks},{count:queuedDeliveries}]=await Promise.all([
 db.from('mission365_organizations').select('*').in('verification_status',['pending','under_review','verified','rejected','suspended']).order('updated_at',{ascending:false}),
 db.from('mission365_applications').select('*').in('status',['submitted','under_review','needs_information']).order('created_at',{ascending:false}),
 db.from('mission365_missions').select('*').in('status',['under_review','paused','rejected']).order('updated_at',{ascending:false}),
 db.from('mission365_impact_updates').select('*').in('status',['submitted','rejected']).order('created_at',{ascending:false}),
 db.from('mission365_milestones').select('*').in('verification_status',['submitted','rejected']).order('created_at',{ascending:false}),
 db.from('mission365_payouts').select('*').in('status',['pending_review','approved','processing','failed','reversed']).order('created_at',{ascending:false}),
 db.from('mission365_risk_events').select('*').eq('status','open').order('created_at',{ascending:false}),
 db.from('mission365_notification_deliveries').select('id',{count:'exact',head:true}).eq('status','queued'),
])
const orgIds=(orgs||[]).map((o:any)=>o.id);const missionIds=Array.from(new Set([...(missions||[]).map((m:any)=>m.id),...(updates||[]).map((u:any)=>u.mission_id),...(milestones||[]).map((m:any)=>m.mission_id),...(payouts||[]).map((p:any)=>p.mission_id)])) as string[]
const [{data:docs},{data:payoutAccounts},{data:audit},{data:missionDetails}]=await Promise.all([
 orgIds.length?db.from('mission365_documents').select('id,application_id,organization_id,mission_id,milestone_id,impact_update_id,document_type,storage_bucket,storage_path,review_status,review_note,rejection_reason,reviewed_by,reviewed_at,created_at').in('organization_id',orgIds).order('created_at',{ascending:false}):Promise.resolve({data:[]}),
 orgIds.length?db.from('mission365_payout_accounts').select('organization_id,stripe_account_id,onboarding_status,transfers_status,requirements_due,last_checked_at,updated_at').in('organization_id',orgIds):Promise.resolve({data:[]}),
 orgIds.length?db.from('mission365_audit_log').select('action,entity_type,entity_id,metadata,created_at').in('entity_id',orgIds).order('created_at',{ascending:false}).limit(200):Promise.resolve({data:[]}),
 missionIds.length?db.from('mission365_missions').select('id,organization_id,title,slug,status,goal_amount_cents,funded_amount_cents,published_at').in('id',missionIds):Promise.resolve({data:[]}),
])
const byOrg=(rows:any[],key='organization_id')=>new Map(orgIds.map((id:string)=>[id,rows.filter((r:any)=>r[key]===id)]));const docsMap=byOrg(docs||[]);const payoutMap=new Map((payoutAccounts||[]).map((p:any)=>[p.organization_id,p]));const auditMap=new Map(orgIds.map((id:string)=>[id,(audit||[]).filter((a:any)=>a.entity_id===id).slice(0,20)]));const appMap=new Map(orgIds.map((id:string)=>[id,(applications||[]).filter((a:any)=>a.organization_id===id)]));const candidates=(orgs||[]).map((o:any)=>({...o,documents:docsMap.get(o.id)||[],payout_account:payoutMap.get(o.id)||null,applications:appMap.get(o.id)||[],actions:auditMap.get(o.id)||[]}))
const {data:stripeKey}=await db.rpc('mission365_get_runtime_secret',{secret_name:'stripe_api_key'});const {data:webhookKey}=await db.rpc('mission365_get_runtime_secret',{secret_name:'stripe_webhook_secret'});return json({role,candidates,applications:applications||[],missions:missions||[],impactUpdates:updates||[],milestones:milestones||[],payouts:payouts||[],riskEvents:risks||[],missionDetails:missionDetails||[],operations:{queuedNotificationDeliveries:queuedDeliveries||0},payments:{stripeApi:Boolean(stripeKey),webhook:Boolean(webhookKey),liveGiving:Boolean(stripeKey&&webhookKey)}})}catch(error){console.error('mission365 admin queue failed',error);return json({error:error instanceof Error?error.message:'Admin queue unavailable'},500)}})
