'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { CalendarDays, MapPin, RefreshCw, Users } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '@/components/MissionAppShell'
import { supabase } from '@/lib/supabase'
import { MISSION365_ENTRY_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY } from '@/lib/mission365-public'

const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export default function VolunteerWorkspace(){
 const [token,setToken]=useState<string|null>(null),[entry,setEntry]=useState<any>(null),[opportunities,setOpportunities]=useState<any[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);const opp=await supabase.from('mission365_volunteer_opportunities').select('id,profile_id,title,description,location,starts_at,ends_at,spots_total,status,mission365_mission_profiles(title,slug,cover_media_url)').in('status',['open','filled','closed']).order('starts_at',{ascending:true,nullsFirst:false});if(opp.error)throw opp.error;setOpportunities(opp.data||[]);if(session){const r=await fetch(MISSION365_ENTRY_URL,{headers:{apikey:MISSION365_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Volunteer workspace unavailable');setEntry(b)}else setEntry(null)}catch(error){setMessage(error instanceof Error?error.message:'Volunteer workspace unavailable')}finally{setBusy(false)}},[])
 useEffect(()=>{void load()},[load])
 const signups=useMemo(()=>new Map((entry?.volunteerSignups||[]).map((s:any)=>[s.opportunity_id,s])),[entry])
 async function post(action:string,payload:any){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_ENTRY_URL,{method:'POST',headers:{apikey:MISSION365_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Volunteer request failed');return b}
 async function run(fn:()=>Promise<any>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success);await load()}catch(error){setMessage(error instanceof Error?error.message:'Volunteer request failed')}finally{setBusy(false)}}
 const active=(entry?.volunteerSignups||[]).filter((s:any)=>['registered','confirmed'].includes(s.status)).length,completed=(entry?.volunteerSignups||[]).filter((s:any)=>s.status==='completed').length
 return <MissionAppShell title="Volunteer Center" subtitle="Give time, skills, labor, mentorship, logistics, and support directly to mission opportunities.">
  <div className="command-bar"><div><p className="eyebrow">VOLUNTEER ENTRY</p><p>Volunteering is a separate participation lane from donating.</p></div><div className="command-actions"><Link className="button button-ghost" href="/join?role=volunteer">Volunteer profile</Link><button className="button button-ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></div>
  {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
  <MetricGrid items={[["Open opportunities",String(opportunities.filter(o=>o.status==='open').length),"Current mission volunteer needs."],["My active signups",token?String(active):'Sign in',"Registered or confirmed opportunities."],["Completed",token?String(completed):'—',"Volunteer participation marked complete."],["Entry level","Volunteer","No donation is required to participate."]]}/>
  <section className="workspace-panel"><div><p className="eyebrow"><Users size={14}/> OPEN OPPORTUNITIES</p><h2>Choose where you can help.</h2></div>{!opportunities.length?<p>No public volunteer opportunities are available yet.</p>:<div className="volunteer-grid">{opportunities.map(o=>{const mission=Array.isArray(o.mission365_mission_profiles)?o.mission365_mission_profiles[0]:o.mission365_mission_profiles,signup=signups.get(o.id) as any;return <article className="role-card" key={o.id}><span className={`status-pill status-${o.status}`}>{label(o.status)}</span><p className="eyebrow">{mission?.title||'Mission 365'}</p><h3>{o.title}</h3><p>{o.description}</p><div className="volunteer-meta">{o.location&&<span><MapPin size={14}/>{o.location}</span>}{o.starts_at&&<span><CalendarDays size={14}/>{new Date(o.starts_at).toLocaleString()}</span>}</div><div className="row-actions wrap">{mission?.slug&&<Link className="button button-ghost button-compact" href={`/missions/${mission.slug}`}>View mission</Link>}{!token?<Link className="button button-compact" href="/login?next=%2Fapp%2Fvolunteer">Sign in to volunteer</Link>:signup&&signup.status!=='cancelled'?<><span className="status-pill status-verified">{label(signup.status)}</span>{['registered','confirmed'].includes(signup.status)&&<button className="button button-ghost button-compact" disabled={busy} onClick={()=>void run(()=>post('cancel_volunteer',{opportunityId:o.id}),'Volunteer registration cancelled.')}>Cancel</button>}</>:o.status==='open'?<button className="button button-compact" disabled={busy} onClick={()=>void run(()=>post('register_volunteer',{opportunityId:o.id}),'You are registered to volunteer.')}>Volunteer for this mission</button>:null}</div></article>})}</div>}</section>
 </MissionAppShell>
}
