'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { FileImage, MessageSquareQuote, Newspaper, RefreshCw, Upload, Users } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '@/components/MissionAppShell'
import { supabase } from '@/lib/supabase'
import { MISSION365_PROFILE_MANAGER_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY, MISSION365_SUPABASE_URL } from '@/lib/mission365-public'

export default function MissionProfileManager(){
 const [token,setToken]=useState<string|null>(null),[userId,setUserId]=useState<string|null>(null),[data,setData]=useState<any>(null),[profileId,setProfileId]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[file,setFile]=useState<File|null>(null)
 const [profile,setProfile]=useState({title:'',summary:'',story:'',category:'',city:'',region:''})
 const [post,setPost]=useState({title:'',body:'',postType:'update'})
 const [testimonial,setTestimonial]=useState({authorName:'',authorRole:'',quote:'',sourceUrl:''})
 const [opportunity,setOpportunity]=useState({title:'',description:'',location:'Atlanta, GA',startsAt:'',endsAt:'',spotsTotal:''})
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);setUserId(session?.user.id||null);if(!session){setData(null);return}const r=await fetch(MISSION365_PROFILE_MANAGER_URL,{headers:{apikey:MISSION365_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Profile manager unavailable');setData(b);const first=b.profiles?.[0]?.id||'';setProfileId(current=>current&&b.profiles?.some((p:any)=>p.id===current)?current:first)}catch(error){setMessage(error instanceof Error?error.message:'Profile manager unavailable')}finally{setBusy(false)}},[])
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
 const current=useMemo(()=>data?.profiles?.find((p:any)=>p.id===profileId)||null,[data,profileId])
 const media=useMemo(()=>data?.media?.filter((x:any)=>x.profile_id===profileId)||[],[data,profileId]),posts=useMemo(()=>data?.posts?.filter((x:any)=>x.profile_id===profileId)||[],[data,profileId]),testimonials=useMemo(()=>data?.testimonials?.filter((x:any)=>x.profile_id===profileId)||[],[data,profileId]),testimonialRequests=useMemo(()=>data?.testimonialRequests?.filter((x:any)=>x.profile_id===profileId)||[],[data,profileId]),opps=useMemo(()=>data?.opportunities?.filter((x:any)=>x.profile_id===profileId)||[],[data,profileId])
 useEffect(()=>{if(!current)return;const timer=window.setTimeout(()=>setProfile({title:current.title||'',summary:current.summary||'',story:current.story||'',category:current.category||'',city:current.city||'',region:current.region||''}),0);return()=>window.clearTimeout(timer)},[current])
 async function postAction(action:string,payload:any={}){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_PROFILE_MANAGER_URL,{method:'POST',headers:{apikey:MISSION365_SUPABASE_PUBLISHABLE_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,profileId,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Profile operation failed');return b}
 async function run(fn:()=>Promise<any>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success);await load()}catch(error){setMessage(error instanceof Error?error.message:'Profile operation failed')}finally{setBusy(false)}}
 async function saveProfile(e:FormEvent){e.preventDefault();await run(()=>postAction('save_profile',profile),'Mission profile saved.')}
 async function uploadMedia(e:FormEvent){e.preventDefault();if(!file||!userId)return;const allowed=['image/jpeg','image/png','image/webp','video/mp4'];if(!allowed.includes(file.type)){setMessage('Upload JPG, PNG, WebP, or MP4 only.');return}if(file.size>10*1024*1024){setMessage('Public profile files must be 10 MB or smaller.');return}await run(async()=>{const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-'),path=`${userId}/${profileId}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from('mission365-public').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const mediaUrl=`${MISSION365_SUPABASE_URL}/storage/v1/object/public/mission365-public/${path}`;await postAction('add_media',{mediaType:file.type==='video/mp4'?'video':'image',mediaUrl,altText:current?.title||'Mission profile media',caption:'',isFeatured:media.length===0,sortOrder:media.length});setFile(null)},'Media uploaded and added to the public profile.')}
 async function addPost(e:FormEvent){e.preventDefault();await run(()=>postAction('add_post',post),'Mission post published.');setPost({title:'',body:'',postType:'update'})}
 async function addTestimonial(e:FormEvent){e.preventDefault();await run(()=>postAction('add_testimonial',testimonial),'Testimonial submitted for verification.');setTestimonial({authorName:'',authorRole:'',quote:'',sourceUrl:''})}
 async function updateTestimonialRequest(id:string,requestStatus:string){await run(()=>postAction('update_testimonial_request',{id,requestStatus}),`Testimonial sourcing status updated to ${requestStatus.replaceAll('_',' ')}.`)}
 async function addOpportunity(e:FormEvent){e.preventDefault();await run(()=>postAction('add_opportunity',{...opportunity,startsAt:opportunity.startsAt?new Date(opportunity.startsAt).toISOString():null,endsAt:opportunity.endsAt?new Date(opportunity.endsAt).toISOString():null,spotsTotal:opportunity.spotsTotal?Number(opportunity.spotsTotal):null}),'Volunteer opportunity opened.');setOpportunity({title:'',description:'',location:'Atlanta, GA',startsAt:'',endsAt:'',spotsTotal:''})}
 if(!token&&!busy)return <MissionAppShell title="Mission Profile Manager" subtitle="Manage the public story, gallery, posts, testimonial submissions, and volunteer opportunities for missions you own."><article className="role-card"><h3>Mission Owner sign-in required.</h3><Link className="button" href="/login?next=%2Fapp%2Fmission-owner%2Fprofile">Sign in securely</Link></article></MissionAppShell>
 if(!current)return <MissionAppShell title="Mission Profile Manager" subtitle="Profiles become editable when your account is an owner or manager of the linked mission organization.">{message&&<article className="role-card notice-card"><strong>{message}</strong></article>}<article className="role-card"><h3>No editable mission profiles yet.</h3><p>Submit or open a Mission Owner workspace first.</p><Link className="button" href="/app/mission-owner">Open Mission Owner workspace</Link></article></MissionAppShell>
 return <MissionAppShell title="Mission Profile Manager" subtitle="Keep each mission profile alive with pictures, videos, posts, testimonials, volunteer opportunities, and updated story content.">
  <div className="command-bar"><div><p className="eyebrow">PUBLIC PROFILE</p><h2 style={{margin:0}}>{current.title}</h2></div><div className="command-actions">{data.profiles.length>1&&<select value={profileId} onChange={e=>setProfileId(e.target.value)}>{data.profiles.map((p:any)=><option value={p.id} key={p.id}>{p.title}</option>)}</select>}<Link className="button button-ghost" href={`/missions/${current.slug}`}>View public profile</Link><button className="button button-ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></div>
  {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
  <MetricGrid items={[["Media",String(media.length),'Pictures and videos on this mission profile.'],["Posts",String(posts.length),'Public profile posts and updates.'],["Testimonials",`${testimonials.length} submitted · ${testimonialRequests.length} sources`,'Quotes stay private until verification; sourcing targets are tracked separately.'],["Volunteer needs",String(opps.length),'Mission-specific volunteer opportunities.']]}/>
  <section className="workspace-panel"><p className="eyebrow">PROFILE STORY</p><h2>Control the mission’s permanent public page.</h2><form className="application-form" onSubmit={saveProfile}><div className="form-grid"><label>Profile title<input value={profile.title} onChange={e=>setProfile({...profile,title:e.target.value})}/></label><label>Category<input value={profile.category} onChange={e=>setProfile({...profile,category:e.target.value})}/></label><label>City<input value={profile.city} onChange={e=>setProfile({...profile,city:e.target.value})}/></label><label>State / region<input value={profile.region} onChange={e=>setProfile({...profile,region:e.target.value})}/></label></div><label>Summary<textarea value={profile.summary} onChange={e=>setProfile({...profile,summary:e.target.value})}/></label><label>Full mission story<textarea value={profile.story} onChange={e=>setProfile({...profile,story:e.target.value})}/></label><button className="button" disabled={busy}>Save profile</button></form></section>
  <section className="workspace-panel"><p className="eyebrow"><FileImage size={14}/> PICTURES + VIDEO</p><h2>Add visual history.</h2><form className="application-form" onSubmit={uploadMedia}><label>Upload public profile media<input type="file" accept="image/jpeg,image/png,image/webp,video/mp4" onChange={e=>setFile(e.target.files?.[0]||null)}/></label><button className="button" disabled={busy||!file}><Upload size={16}/>Upload to profile</button></form><div className="mission-gallery">{media.map((m:any)=><figure className="gallery-tile" key={m.id}>{m.media_type==='video'?<video src={m.media_url} controls playsInline/>:<img src={m.media_url} alt={m.alt_text||current.title}/>}<figcaption>{m.caption||m.alt_text}</figcaption></figure>)}</div></section>
  <section className="workspace-panel"><p className="eyebrow"><Newspaper size={14}/> POSTS</p><h2>Publish mission activity.</h2><form className="application-form" onSubmit={addPost}><div className="form-grid"><label>Post title<input value={post.title} onChange={e=>setPost({...post,title:e.target.value})} required/></label><label>Post type<select value={post.postType} onChange={e=>setPost({...post,postType:e.target.value})}><option value="update">Update</option><option value="story">Story</option><option value="event">Event</option><option value="press">Press</option><option value="impact">Impact</option></select></label></div><label>Post body<textarea value={post.body} onChange={e=>setPost({...post,body:e.target.value})} required/></label><button className="button" disabled={busy}>Publish post</button></form><div className="record-list">{posts.map((p:any)=><div className="record-row" key={p.id}><div><strong>{p.title}</strong><small>{p.post_type.replaceAll('_',' ')} · {p.status}</small></div></div>)}</div></section>
  <section className="workspace-panel"><p className="eyebrow"><MessageSquareQuote size={14}/> TESTIMONIAL SOURCING QUEUE</p><h2>Find the real voices before publishing quotes.</h2><p>These are sourcing targets, not testimonials. A quote still must be submitted below and independently verified before it can appear publicly.</p><div className="record-list">{testimonialRequests.map((r:any)=><div className="record-row" key={r.id}><div><strong>{r.target_role}</strong><small>{r.request_status.replaceAll('_',' ')} · consent {r.consent_status.replaceAll('_',' ')}{r.anonymity_allowed?' · anonymity allowed':''}</small><p>{r.notes}</p></div><div className="row-actions wrap">{r.request_status==='queued'&&<button className="button button-ghost button-compact" disabled={busy} onClick={()=>void updateTestimonialRequest(r.id,'sent')}>Mark contacted</button>}{r.request_status==='sent'&&<button className="button button-ghost button-compact" disabled={busy} onClick={()=>void updateTestimonialRequest(r.id,'responded')}>Mark responded</button>}</div></div>)}</div></section>
  <section className="workspace-panel"><p className="eyebrow"><MessageSquareQuote size={14}/> TESTIMONIALS</p><h2>Submit real quotes for verification.</h2><p>Mission owners can submit testimonials, but they do not display publicly until the source is verified.</p><form className="application-form" onSubmit={addTestimonial}><div className="form-grid"><label>Person’s name<input value={testimonial.authorName} onChange={e=>setTestimonial({...testimonial,authorName:e.target.value})} required/></label><label>Role / relationship<input value={testimonial.authorRole} onChange={e=>setTestimonial({...testimonial,authorRole:e.target.value})}/></label></div><label>Quote<textarea value={testimonial.quote} onChange={e=>setTestimonial({...testimonial,quote:e.target.value})} required/></label><label>Source URL / proof (optional)<input type="url" placeholder="https://" value={testimonial.sourceUrl} onChange={e=>setTestimonial({...testimonial,sourceUrl:e.target.value})}/></label><button className="button" disabled={busy}>Submit testimonial</button></form><div className="record-list">{testimonials.map((t:any)=><div className="record-row" key={t.id}><div><strong>{t.author_name}</strong><small>{t.verification_status.replaceAll('_',' ')} · {t.status}</small><p>{t.quote}</p></div></div>)}</div></section>
  <section className="workspace-panel"><p className="eyebrow"><Users size={14}/> VOLUNTEER OPPORTUNITIES</p><h2>Ask for people, not only money.</h2><form className="application-form" onSubmit={addOpportunity}><div className="form-grid"><label>Opportunity title<input value={opportunity.title} onChange={e=>setOpportunity({...opportunity,title:e.target.value})} required/></label><label>Location<input value={opportunity.location} onChange={e=>setOpportunity({...opportunity,location:e.target.value})}/></label><label>Starts<input type="datetime-local" value={opportunity.startsAt} onChange={e=>setOpportunity({...opportunity,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" value={opportunity.endsAt} onChange={e=>setOpportunity({...opportunity,endsAt:e.target.value})}/></label><label>Volunteer spots<input type="number" min="1" value={opportunity.spotsTotal} onChange={e=>setOpportunity({...opportunity,spotsTotal:e.target.value})}/></label></div><label>Description<textarea value={opportunity.description} onChange={e=>setOpportunity({...opportunity,description:e.target.value})}/></label><button className="button" disabled={busy}>Open volunteer opportunity</button></form><div className="record-list">{opps.map((o:any)=><div className="record-row" key={o.id}><div><strong>{o.title}</strong><small>{o.status} · {o.location||'Location TBD'}</small></div>{o.status==='open'&&<button className="button button-ghost button-compact" onClick={()=>void run(()=>postAction('close_opportunity',{id:o.id}),'Volunteer opportunity closed.')}>Close</button>}</div>)}</div></section>
 </MissionAppShell>
}
