'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { BadgeCheck, CircleDashed, ExternalLink, FileUp, Landmark, RefreshCw, Send, WalletCards } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '../../../components/MissionAppShell'
import { supabase } from '../../../lib/supabase'
import { MISSION365_CONNECT_URL, MISSION365_OWNER_PORTAL_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY } from '../../../lib/mission365-public'

const headers={'apikey':MISSION365_SUPABASE_PUBLISHABLE_KEY}
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const money=(c:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format((Number(c)||0)/100)
const docOptions=[['authorized_rep_id','Authorized representative ID'],['formation_document','Formation / registration document'],['ein_or_tax_id','EIN / tax ID'],['tax_exempt_status','Tax-exempt status'],['program_evidence','Program / mission evidence'],['milestone_evidence','Milestone evidence'],['impact_evidence','Impact evidence'],['other','Other evidence']]

export default function MissionOwnerWorkspace(){
 const [portal,setPortal]=useState<any>(null),[token,setToken]=useState<string|null>(null),[userId,setUserId]=useState<string|null>(null),[orgId,setOrgId]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[termsAccepted,setTermsAccepted]=useState(false)
 const [profile,setProfile]=useState({legal_name:'',public_name:'',organization_type:'community_project',website_url:''})
 const [mission,setMission]=useState({title:'',summary:'',story:'',category:'Community',goalAmount:'5000',city:'',region:'',fundingClosesAt:''})
 const [milestone,setMilestone]=useState({title:'',description:'',targetDate:''}),[impact,setImpact]=useState({title:'',body:''}),[payoutAmount,setPayoutAmount]=useState('')
 const [file,setFile]=useState<File|null>(null),[docType,setDocType]=useState('authorized_rep_id'),[evidenceTarget,setEvidenceTarget]=useState('verification')

 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);setUserId(session?.user.id||null);if(!session){setPortal(null);return}const [response,terms]=await Promise.all([fetch(MISSION365_OWNER_PORTAL_URL,{headers:{...headers,Authorization:`Bearer ${session.access_token}`},cache:'no-store'}),supabase.from('mission365_terms_acceptances').select('id').eq('document_key','mission_owner_terms').eq('version','2026-08-08').maybeSingle()]);const body=await response.json();if(!response.ok)throw new Error(body.error||'Owner workspace unavailable');setPortal(body);setTermsAccepted(Boolean(terms.data));const first=body.organizations?.[0]?.id||'';setOrgId((current:string)=>current&&body.organizations?.some((o:any)=>o.id===current)?current:first)}catch(error){setMessage(error instanceof Error?error.message:'Owner workspace unavailable')}finally{setBusy(false)}},[])
 useEffect(()=>{void load()},[load])
 const org=useMemo(()=>portal?.organizations?.find((o:any)=>o.id===orgId)||null,[portal,orgId]);const missions=useMemo(()=>portal?.missions?.filter((m:any)=>m.organization_id===orgId)||[],[portal,orgId]);const primaryMission=missions.find((m:any)=>m.status==='draft')||missions[0]||null;const payoutAccount=portal?.payoutAccounts?.find((p:any)=>p.organization_id===orgId)||null;const docs=portal?.documents?.filter((d:any)=>d.organization_id===orgId)||[];const milestones=primaryMission?portal?.milestones?.filter((m:any)=>m.mission_id===primaryMission.id)||[]:[];const impacts=primaryMission?portal?.impactUpdates?.filter((u:any)=>u.mission_id===primaryMission.id)||[]:[];const payouts=portal?.payouts?.filter((p:any)=>p.organization_id===orgId)||[];const ownerApps=portal?.applications?.filter((a:any)=>a.application_type==='mission_owner')||[]
 useEffect(()=>{if(org)setProfile({legal_name:org.legal_name,public_name:org.public_name,organization_type:org.organization_type,website_url:org.website_url||''})},[org])
 async function owner(action:string,payload:any={}){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_OWNER_PORTAL_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Operation failed');return b}
 async function connect(action:string,payload:any={}){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_CONNECT_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,organizationId:orgId,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Stripe onboarding operation failed');return b}
 async function run(fn:()=>Promise<any>,success:string,refresh=true){setBusy(true);setMessage('');try{await fn();setMessage(success);if(refresh)await load()}catch(error){setMessage(error instanceof Error?error.message:'Operation failed')}finally{setBusy(false)}}
 async function initialize(id:string){await run(()=>owner('initialize_workspace',{applicationId:id}),'Verification workspace created.')}
 async function saveProfile(e:FormEvent){e.preventDefault();await run(()=>owner('save_organization',{organizationId:orgId,...profile}),'Organization profile saved.')}
 async function acceptTerms(){await run(async()=>{if(!userId)throw new Error('Sign in required');const {error}=await supabase.from('mission365_terms_acceptances').upsert({user_id:userId,document_key:'mission_owner_terms',version:'2026-08-08',metadata:{surface:'mission_owner_workspace'}},{onConflict:'user_id,document_key,version',ignoreDuplicates:true});if(error)throw error;setTermsAccepted(true)},'Mission Owner agreement accepted.',false)}
 async function beginOnboarding(){await run(async()=>{if(!payoutAccount)await connect('create_account');const link=await connect('hosted_onboarding');window.location.assign(link.url)},'Opening Stripe onboarding…',false)}
 async function openExpress(){await run(async()=>{const b=await connect('express_login');window.open(b.url,'_blank','noopener,noreferrer')},'Stripe Express opened.',false)}
 async function saveMission(e:FormEvent){e.preventDefault();await run(()=>owner('save_mission',{organizationId:orgId,mission:{...mission,id:primaryMission?.status==='draft'?primaryMission.id:undefined,goalAmount:Number(mission.goalAmount),fundingClosesAt:mission.fundingClosesAt?`${mission.fundingClosesAt}T23:59:59Z`:null}}),'Mission draft saved.')}
 async function saveMilestone(e:FormEvent){e.preventDefault();if(!primaryMission)return;await run(()=>owner('save_milestone',{missionId:primaryMission.id,milestone:{title:milestone.title,description:milestone.description,targetDate:milestone.targetDate||null,sortOrder:milestones.length}}),'Milestone saved.');setMilestone({title:'',description:'',targetDate:''})}
 async function saveImpact(e:FormEvent){e.preventDefault();if(!primaryMission)return;await run(()=>owner('save_impact',{missionId:primaryMission.id,impactUpdate:{title:impact.title,body:impact.body}}),'Impact update draft saved.');setImpact({title:'',body:''})}
 async function upload(e:FormEvent){e.preventDefault();if(!file||!userId||!orgId) return;if(file.size>10*1024*1024){setMessage('Files must be 10 MB or smaller.');return}const allowed=['application/pdf','image/jpeg','image/png','image/webp'];if(!allowed.includes(file.type)){setMessage('Upload PDF, JPG, PNG, or WebP only.');return}await run(async()=>{const safe=file.name.replace(/[^a-zA-Z0-9._-]+/g,'-');const path=`${userId}/${orgId}/${Date.now()}-${safe}`;const {error}=await supabase.storage.from('mission365-private').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;const payload:any={organizationId:orgId,documentType:docType,storagePath:path};if(evidenceTarget.startsWith('milestone:')){payload.missionId=primaryMission?.id;payload.milestoneId=evidenceTarget.split(':')[1]}else if(evidenceTarget.startsWith('impact:')){payload.missionId=primaryMission?.id;payload.impactUpdateId=evidenceTarget.split(':')[1]}else if(evidenceTarget==='mission'){payload.missionId=primaryMission?.id}else{payload.applicationId=ownerApps.find((a:any)=>a.organization_id===orgId)?.id||null}await owner('register_document',payload);setFile(null)},'Evidence uploaded privately.')}
 async function requestPayout(e:FormEvent){e.preventDefault();if(!primaryMission)return;await run(()=>owner('request_payout',{missionId:primaryMission.id,amount:Number(payoutAmount)}),'Payout request submitted.');setPayoutAmount('')}

 if(!token&&!busy)return <MissionAppShell title="Mission Owner Workspace" subtitle="Verification, mission publishing, evidence, milestones, and payout readiness."><article className="role-card"><h3>Sign in required.</h3><p>Private verification and payout records are available only to authenticated organization members.</p><Link className="button" href="/login">Sign in securely</Link></article></MissionAppShell>
 if(!org)return <MissionAppShell title="Mission Owner Workspace" subtitle="Start with a private mission-owner application.">{message&&<article className="role-card"><strong>{message}</strong></article>}{ownerApps.length?ownerApps.map((a:any)=><article className="role-card" key={a.id}><p className="eyebrow">{label(a.status)}</p><h3>{a.public_name}</h3><p>{a.mission_summary}</p><button className="button" onClick={()=>void initialize(a.id)}>Create / open verification workspace</button></article>):<article className="role-card"><h3>No mission-owner application yet.</h3><Link className="button" href="/apply">Submit an application</Link></article>}</MissionAppShell>

 const accepted=docs.filter((d:any)=>d.review_status==='accepted').length;const available=Math.max(0,Number(primaryMission?.funded_amount_cents||0)-payouts.filter((p:any)=>['pending_review','approved','processing','paid'].includes(p.status)).reduce((n:number,p:any)=>n+Number(p.amount_cents||0),0))
 return <MissionAppShell title="Mission Owner Workspace" subtitle="Verification, Stripe onboarding, mission building, milestones, impact reporting, and payout requests in one operating workspace.">
  <div className="command-bar"><div><p className="eyebrow">{org.public_name}</p><h2 style={{margin:0}}>{label(org.verification_status)}</h2></div><div className="command-actions"><button className="button button-ghost" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</button>{portal.organizations.length>1&&<select value={orgId} onChange={e=>setOrgId(e.target.value)}>{portal.organizations.map((o:any)=><option value={o.id} key={o.id}>{o.public_name}</option>)}</select>}</div></div>
  {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
  <MetricGrid items={[["Verification",label(org.verification_status),`${accepted} accepted verification document(s).`],["Stripe payout",payoutAccount?label(payoutAccount.onboarding_status):'Not started',payoutAccount?.transfers_status==='active'?'Transfers active.':'Publication stays locked until transfers are active.'],["Mission",primaryMission?label(primaryMission.status):'No draft',primaryMission?`${money(primaryMission.funded_amount_cents)} recorded of ${money(primaryMission.goal_amount_cents)} goal.`:'Create your first mission draft.'],["Available payout",money(available),'Subject to cleared proceeds, risk review, and finance approval.']]}/>

  <section className="workspace-panel"><div><p className="eyebrow">1 · ORGANIZATION VERIFICATION</p><h2>Keep the record accurate.</h2></div><form className="application-form" onSubmit={saveProfile}><div className="form-grid"><label>Legal name<input value={profile.legal_name} onChange={e=>setProfile({...profile,legal_name:e.target.value})}/></label><label>Public name<input value={profile.public_name} onChange={e=>setProfile({...profile,public_name:e.target.value})}/></label><label>Organization type<select value={profile.organization_type} onChange={e=>setProfile({...profile,organization_type:e.target.value})}><option value="community_project">Community project</option><option value="nonprofit">Nonprofit</option><option value="school">School</option><option value="faith_organization">Faith organization</option><option value="individual_mission">Individual mission</option></select></label><label>Website<input type="url" value={profile.website_url} onChange={e=>setProfile({...profile,website_url:e.target.value})} placeholder="https://"/></label></div><button className="button" disabled={busy}>Save organization</button></form><div className="record-list">{docs.filter((d:any)=>!d.milestone_id&&!d.impact_update_id).map((d:any)=><div className="record-row" key={d.id}><div><strong>{label(d.document_type)}</strong><small>{label(d.review_status)}{d.review_note?` · ${d.review_note}`:''}{d.rejection_reason?` · ${d.rejection_reason}`:''}</small></div><span>{new Date(d.created_at).toLocaleDateString()}</span></div>)}</div></section>

  <section className="workspace-panel"><div><p className="eyebrow">2 · STRIPE RECIPIENT ONBOARDING</p><h2>Connect payouts after verification.</h2><p>Mission 365 uses a connected Stripe recipient account. Organization verification can complete before Stripe onboarding; mission publication cannot.</p></div>{org.verification_status!=='verified'?<article className="role-card"><CircleDashed/><h3>Finish verification first.</h3></article>:<div className="row-actions wrap">{!payoutAccount?<button className="button" onClick={()=>void beginOnboarding()}><Landmark size={17}/>Create & start Stripe onboarding</button>:payoutAccount.transfers_status!=='active'?<><button className="button" onClick={()=>void beginOnboarding()}><Landmark size={17}/>Continue Stripe onboarding</button><button className="button button-ghost" onClick={()=>void run(()=>connect('refresh'),'Stripe status refreshed.')}>Refresh status</button></>:<><button className="button" onClick={()=>void openExpress()}><ExternalLink size={17}/>Open Stripe Express</button><button className="button button-ghost" onClick={()=>void run(()=>connect('refresh'),'Stripe status refreshed.')}>Refresh status</button></>}</div>}</section>

  <section className="workspace-panel"><div><p className="eyebrow">3 · AGREEMENT & MISSION BUILDER</p><h2>Build a measurable mission.</h2></div><div className="row-actions wrap">{termsAccepted?<span className="status-pill status-verified"><BadgeCheck size={14}/>Mission Owner agreement accepted</span>:<button className="button" onClick={()=>void acceptTerms()}>Accept Mission Owner agreement</button>}<Link className="button button-ghost" href="/legal#mission-owner">Review agreement</Link></div><form className="application-form" onSubmit={saveMission}><div className="form-grid"><label>Mission title<input value={mission.title} onChange={e=>setMission({...mission,title:e.target.value})} required/></label><label>Category<input value={mission.category} onChange={e=>setMission({...mission,category:e.target.value})} required/></label><label>Goal USD<input type="number" min="1" value={mission.goalAmount} onChange={e=>setMission({...mission,goalAmount:e.target.value})} required/></label><label>Funding close date<input type="date" value={mission.fundingClosesAt} onChange={e=>setMission({...mission,fundingClosesAt:e.target.value})}/></label><label>City<input value={mission.city} onChange={e=>setMission({...mission,city:e.target.value})}/></label><label>State / region<input value={mission.region} onChange={e=>setMission({...mission,region:e.target.value})}/></label></div><label>Summary<textarea value={mission.summary} onChange={e=>setMission({...mission,summary:e.target.value})} minLength={20} required/></label><label>Full story / use of funds<textarea value={mission.story} onChange={e=>setMission({...mission,story:e.target.value})} minLength={40} required/></label><button className="button" disabled={busy}>Save mission draft</button></form>{primaryMission?.status==='draft'&&<button className="button" style={{marginTop:14}} disabled={busy} onClick={()=>void run(()=>owner('submit_mission',{missionId:primaryMission.id}),'Mission submitted for final review.')}><Send size={16}/>Submit mission for review</button>}</section>

  {primaryMission&&<section className="workspace-panel"><div><p className="eyebrow">4 · MILESTONES</p><h2>Define and verify outcomes.</h2></div><form className="application-form" onSubmit={saveMilestone}><div className="form-grid"><label>Milestone title<input value={milestone.title} onChange={e=>setMilestone({...milestone,title:e.target.value})} required/></label><label>Target date<input type="date" value={milestone.targetDate} onChange={e=>setMilestone({...milestone,targetDate:e.target.value})}/></label></div><label>Measurable description<textarea value={milestone.description} onChange={e=>setMilestone({...milestone,description:e.target.value})} minLength={15} required/></label><button className="button">Add milestone</button></form><div className="record-list">{milestones.map((m:any)=><div className="record-row" key={m.id}><div><strong>{m.title}</strong><small>{label(m.verification_status)} · {m.target_date||'No target date'}{m.review_note?` · ${m.review_note}`:''}</small></div>{['pending','rejected'].includes(m.verification_status)&&<button className="button button-ghost button-compact" onClick={()=>void run(()=>owner('submit_milestone',{milestoneId:m.id}),'Milestone submitted for evidence review.')}>Submit for verification</button>}</div>)}</div></section>}

  {primaryMission&&<section className="workspace-panel"><div><p className="eyebrow">5 · PRIVATE EVIDENCE</p><h2>Attach proof to verification, milestones, or impact updates.</h2></div><form className="application-form" onSubmit={upload}><div className="form-grid"><label>Evidence type<select value={docType} onChange={e=>setDocType(e.target.value)}>{docOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Attach to<select value={evidenceTarget} onChange={e=>setEvidenceTarget(e.target.value)}><option value="verification">Organization verification</option><option value="mission">Mission record</option>{milestones.map((m:any)=><option key={m.id} value={`milestone:${m.id}`}>Milestone: {m.title}</option>)}{impacts.map((u:any)=><option key={u.id} value={`impact:${u.id}`}>Impact: {u.title}</option>)}</select></label></div><label>PDF/JPG/PNG/WebP<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} required/></label><button className="button" disabled={!file||busy}><FileUp size={16}/>Upload privately</button></form></section>}

  {primaryMission&&<section className="workspace-panel"><div><p className="eyebrow">6 · IMPACT REPORTING</p><h2>Tell supporters what happened next.</h2></div><form className="application-form" onSubmit={saveImpact}><label>Update title<input value={impact.title} onChange={e=>setImpact({...impact,title:e.target.value})} required/></label><label>Outcome details<textarea value={impact.body} onChange={e=>setImpact({...impact,body:e.target.value})} minLength={40} required/></label><button className="button">Save impact draft</button></form><div className="record-list">{impacts.map((u:any)=><div className="record-row" key={u.id}><div><strong>{u.title}</strong><small>{label(u.status)}{u.review_note?` · ${u.review_note}`:''}</small></div>{['draft','rejected'].includes(u.status)&&<button className="button button-ghost button-compact" onClick={()=>void run(()=>owner('submit_impact',{impactUpdateId:u.id}),'Impact update submitted for review.')}>Submit</button>}</div>)}</div></section>}

  {primaryMission&&['published','funded','reporting','completed'].includes(primaryMission.status)&&<section className="workspace-panel"><div><p className="eyebrow">7 · PAYOUT REQUESTS</p><h2>Request only cleared mission proceeds.</h2></div><form className="application-form" onSubmit={requestPayout}><label>Requested amount USD<input type="number" min="1" step="1" value={payoutAmount} onChange={e=>setPayoutAmount(e.target.value)} required/></label><button className="button"><WalletCards size={16}/>Request payout</button></form><div className="record-list">{payouts.map((p:any)=><div className="record-row" key={p.id}><div><strong>{money(p.amount_cents)}</strong><small>{label(p.status)}{p.failure_reason?` · ${p.failure_reason}`:''}</small></div><span>{p.requested_at?new Date(p.requested_at).toLocaleDateString():new Date(p.created_at).toLocaleDateString()}</span></div>)}</div></section>}
 </MissionAppShell>
}
