'use client'

import { useCallback, useEffect, useState } from 'react'
import Link from 'next/link'
import { Bell, Bookmark, Download, ExternalLink, RefreshCw, ReceiptText, Settings2 } from 'lucide-react'
import { MissionAppShell, MetricGrid } from '../../../components/MissionAppShell'
import { supabase } from '../../../lib/supabase'
import { MISSION365_DONOR_DASHBOARD_URL, MISSION365_SUPABASE_PUBLISHABLE_KEY } from '../../../lib/mission365-public'

const headers={'apikey':MISSION365_SUPABASE_PUBLISHABLE_KEY}
const money=(c:number,currency='usd')=>new Intl.NumberFormat('en-US',{style:'currency',currency:currency.toUpperCase(),maximumFractionDigits:2}).format((Number(c)||0)/100)
const label=(v:string)=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
export default function DonorWorkspace(){
 const [data,setData]=useState<any>(null),[token,setToken]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [prefs,setPrefs]=useState({inApp:true,email:true,sms:false})
 const load=useCallback(async()=>{setBusy(true);setMessage('');try{const {data:{session}}=await supabase.auth.getSession();setToken(session?.access_token||null);if(!session){setData(null);return}const r=await fetch(MISSION365_DONOR_DASHBOARD_URL,{headers:{...headers,Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const b=await r.json();if(!r.ok)throw new Error(b.error||'Donor dashboard unavailable');setData(b);setPrefs({inApp:b.preferences?.in_app_enabled!==false,email:b.preferences?.email_enabled!==false,sms:b.preferences?.sms_enabled===true})}catch(error){setMessage(error instanceof Error?error.message:'Donor dashboard unavailable')}finally{setBusy(false)}},[])
 useEffect(()=>{void load()},[load])
 async function post(action:string,payload:any={}){if(!token)throw new Error('Sign in required');const r=await fetch(MISSION365_DONOR_DASHBOARD_URL,{method:'POST',headers:{...headers,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Operation failed');return b}
 async function run(fn:()=>Promise<any>,success:string,refresh=true){setBusy(true);setMessage('');try{await fn();setMessage(success);if(refresh)await load()}catch(error){setMessage(error instanceof Error?error.message:'Operation failed')}finally{setBusy(false)}}
 const termsAccepted=Boolean(data?.terms?.some((t:any)=>t.document_key==='donor_terms'&&t.version==='2026-08-08'))
 function downloadReport(){if(!data)return;const rows=[['Date','Mission','Status','Gross USD','Refunded USD','Net USD'],...data.donations.map((d:any)=>[(d.succeeded_at||d.created_at||'').slice(0,10),d.mission?.title||d.mission_id,d.status,(Number(d.amount_cents)/100).toFixed(2),(Number(d.refunded_amount_cents||0)/100).toFixed(2),((Number(d.amount_cents)-Number(d.refunded_amount_cents||0))/100).toFixed(2)])];const csv=rows.map((r:any[])=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`mission365-giving-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url)}
 if(!token&&!busy)return <MissionAppShell title="Donor Dashboard" subtitle="Your giving, recurring plans, receipts, saved missions, and verified impact."><article className="role-card"><h3>Sign in to see your private giving ledger.</h3><Link className="button" href="/login">Sign in securely</Link></article></MissionAppShell>
 return <MissionAppShell title="Donor Dashboard" subtitle="Live giving, recurring-plan management, receipts, saved missions, notifications, and verified impact from your Mission 365 ledger.">
  <div className="command-bar"><div><p className="eyebrow">PRIVATE DONOR LEDGER</p><p>Only recorded transactions appear in totals.</p></div><div className="command-actions"><button className="button button-ghost" onClick={downloadReport}><Download size={16}/>Export giving</button><button className="button button-ghost" onClick={()=>void load()} disabled={busy}><RefreshCw size={16}/>Refresh</button></div></div>
  {message&&<article className="role-card notice-card"><strong>{message}</strong></article>}
  <MetricGrid items={[["Giving this year",data?money(data.metrics.givingThisYearCents):'—','Net recorded giving after refunds.'],["Active monthly plans",data?String(data.metrics.activePlans):'—','Recurring Mission 365 giving plans.'],["Missions supported",data?String(data.metrics.missionsSupported):'—','Unique missions with recorded giving.'],["Saved missions",data?String(data.metrics.savedMissions):'—','Missions bookmarked for later.'],["Unread notices",data?String(data.metrics.unreadNotifications):'—','Giving and impact updates needing attention.']]}/>

  <section className="workspace-panel"><div><p className="eyebrow">GIVING AGREEMENT</p><h2>Give with clear terms.</h2><p>Mission 365 does not represent every contribution as tax-deductible. Deductibility depends on the verified recipient and applicable tax rules.</p></div><div className="row-actions wrap">{termsAccepted?<span className="status-pill status-verified">Donor terms accepted · 2026-08-08</span>:<button className="button" onClick={()=>void run(()=>post('accept_terms',{documentKey:'donor_terms'}),'Donor terms accepted.')}>Accept donor terms</button>}<Link className="button button-ghost" href="/legal#donor">Review donor/refund policy</Link></div></section>

  <section className="workspace-panel"><div><p className="eyebrow">RECURRING GIVING</p><h2>Manage plans and payment methods.</h2></div><div className="row-actions wrap"><button className="button" onClick={()=>void run(async()=>{const b=await post('customer_portal');window.location.assign(b.url)},'Opening secure Stripe portal…',false)}><ExternalLink size={16}/>Open Stripe Customer Portal</button><Link className="button button-ghost" href="/missions">Explore verified missions</Link></div><div className="record-list">{data?.plans?.length?data.plans.map((p:any)=><div className="record-row" key={p.id}><div><strong>{p.mission?.title||'Mission 365 giving plan'}</strong><small>{label(p.cadence)} · {label(p.status)}</small></div><span>{money(p.amount_cents)}</span></div>):<p>No giving plans yet.</p>}</div></section>

  <section className="workspace-panel"><div><p className="eyebrow"><ReceiptText size={14}/> RECENT GIVING & RECEIPTS</p><h2>Your recorded transaction history.</h2></div><div className="record-list">{data?.donations?.length?data.donations.slice(0,20).map((d:any)=><div className="record-row" key={d.id}><div><strong>{d.mission?.title||'Mission'}</strong><small>{new Date(d.succeeded_at||d.created_at).toLocaleDateString()} · {label(d.status)}{Number(d.refunded_amount_cents)>0?` · refunded ${money(d.refunded_amount_cents,d.currency)}`:''}</small></div><span>{money(Math.max(0,Number(d.amount_cents)-Number(d.refunded_amount_cents||0)),d.currency)}</span></div>):<p>No recorded donations yet.</p>}</div><div className="record-list">{data?.receipts?.map((r:any)=><div className="record-row" key={r.id}><div><strong><ReceiptText size={15}/>{r.receipt_number}</strong><small>{new Date(r.issued_at).toLocaleDateString()} · Transaction record; tax treatment depends on verified recipient status.</small></div><span>{money(r.amount_cents,r.currency)}</span></div>)}</div></section>

  <section className="workspace-panel"><div><p className="eyebrow"><Bookmark size={14}/> SAVED MISSIONS</p><h2>Come back to causes you care about.</h2></div>{!data?.savedMissions?.length?<p>No saved missions yet. Save from a verified mission page.</p>:<div className="record-list">{data.savedMissions.map((s:any)=><div className="record-row" key={s.mission_id}><div><strong>{s.mission?.title||'Saved mission'}</strong><small>{s.mission?label(s.mission.status):''}</small></div><div className="row-actions"><Link className="button button-ghost button-compact" href={`/missions/${s.mission?.slug}`}>View</Link><button className="button button-ghost button-compact" onClick={()=>void run(()=>post('unsave_mission',{missionId:s.mission_id}),'Mission removed from saved list.')}>Remove</button></div></div>)}</div>}</section>

  <section className="workspace-panel"><div><p className="eyebrow">VERIFIED IMPACT TIMELINE</p><h2>Follow what happened after funding.</h2></div>{!data?.impactUpdates?.length?<p>No published impact updates yet.</p>:<div className="record-list">{data.impactUpdates.map((u:any)=><div className="record-row" key={u.id}><div><strong>{u.title}</strong><small>{new Date(u.published_at).toLocaleDateString()}</small><p>{u.body}</p></div></div>)}</div>}</section>

  <section className="workspace-panel"><div><p className="eyebrow"><Bell size={14}/> NOTIFICATIONS</p><h2>Control how Mission 365 reaches you.</h2></div><div className="preference-grid"><label><input type="checkbox" checked={prefs.inApp} onChange={e=>setPrefs({...prefs,inApp:e.target.checked})}/> In-app</label><label><input type="checkbox" checked={prefs.email} onChange={e=>setPrefs({...prefs,email:e.target.checked})}/> Email</label><label><input type="checkbox" checked={prefs.sms} onChange={e=>setPrefs({...prefs,sms:e.target.checked})}/> SMS (requires verified phone)</label></div><button className="button button-ghost" onClick={()=>void run(()=>post('update_preferences',{inAppEnabled:prefs.inApp,emailEnabled:prefs.email,smsEnabled:prefs.sms,categories:{giving:true,verification:true,impact:true,payouts:true,risk:true}}),'Notification preferences saved.')}><Settings2 size={16}/>Save preferences</button><div className="record-list">{data?.notifications?.slice(0,20).map((n:any)=><div className="record-row" key={n.id}><div><strong>{n.title}</strong><small>{new Date(n.created_at).toLocaleString()}</small><p>{n.body}</p></div>{!n.read_at&&<button className="button button-ghost button-compact" onClick={()=>void run(()=>post('mark_notification_read',{notificationId:n.id}),'Notification marked read.')}>Mark read</button>}</div>)}</div></section>
 </MissionAppShell>
}
