import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'GET, POST, OPTIONS'}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'cache-control':'no-store'}})
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function db(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function scoped(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
function cleanHttpsUrl(value:unknown){const text=String(value||'').trim();if(!text)return null;try{const url=new URL(text);return url.protocol==='https:'?url.toString():null}catch{return null}}
async function userFor(req:Request){const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return {error:json({error:'Authentication required'},401)};const {data:{user},error}=await scoped(auth).auth.getUser(token);if(error||!user)return {error:json({error:'Invalid session'},401)};return {user}}
async function accessibleProfileIds(admin:any,userId:string){const {data:members}=await admin.from('mission365_organization_members').select('organization_id,member_role').eq('user_id',userId).in('member_role',['owner','manager']);const orgIds=(members||[]).map((m:any)=>m.organization_id);if(!orgIds.length)return [] as string[];const {data:missions}=await admin.from('mission365_missions').select('id').in('organization_id',orgIds);const missionIds=(missions||[]).map((m:any)=>m.id);if(!missionIds.length)return [] as string[];const {data:profiles}=await admin.from('mission365_mission_profiles').select('id').in('mission_id',missionIds);return (profiles||[]).map((p:any)=>p.id)}
async function assertProfile(admin:any,userId:string,profileId:string){const ids=await accessibleProfileIds(admin,userId);return ids.includes(profileId)}
async function snapshot(admin:any,userId:string){const ids=await accessibleProfileIds(admin,userId);if(!ids.length)return {profiles:[],media:[],posts:[],testimonials:[],testimonialRequests:[],opportunities:[]};const [{data:profiles},{data:media},{data:posts},{data:testimonials},{data:testimonialRequests},{data:opps}]=await Promise.all([admin.from('mission365_mission_profiles').select('*').in('id',ids).order('title'),admin.from('mission365_mission_media').select('*').in('profile_id',ids).order('sort_order'),admin.from('mission365_mission_posts').select('*').in('profile_id',ids).order('created_at',{ascending:false}),admin.from('mission365_mission_testimonials').select('*').in('profile_id',ids).order('created_at',{ascending:false}),admin.from('mission365_testimonial_requests').select('*').in('profile_id',ids).order('created_at',{ascending:true}),admin.from('mission365_volunteer_opportunities').select('*').in('profile_id',ids).order('created_at',{ascending:false})]);return {profiles:profiles||[],media:media||[],posts:posts||[],testimonials:testimonials||[],testimonialRequests:testimonialRequests||[],opportunities:opps||[]}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(!['GET','POST'].includes(req.method))return json({error:'Method not allowed'},405);try{const auth=await userFor(req);if('error' in auth)return auth.error;const user=auth.user!,admin=db();if(req.method==='GET')return json(await snapshot(admin,user.id));const body=await req.json(),action=String(body?.action||''),profileId=String(body?.profileId||'');if(!profileId||!(await assertProfile(admin,user.id,profileId)))return json({error:'Mission owner or manager access required for this profile'},403);
 if(action==='save_profile'){const patch:any={updated_at:new Date().toISOString()};for(const key of ['title','summary','story','category','city','region'])if(body[key]!==undefined)patch[key]=body[key]===null?null:String(body[key]).trim();for(const key of ['cover_media_url','logo_url'])if(body[key]!==undefined){const raw=String(body[key]||'').trim();const safe=cleanHttpsUrl(raw);if(raw&&!safe)return json({error:`${key} must be a valid https URL`},400);patch[key]=safe}const {data,error}=await admin.from('mission365_mission_profiles').update(patch).eq('id',profileId).select('*').single();if(error)throw error;return json({profile:data})}
 if(action==='add_media'){const mediaType=String(body?.mediaType||''),url=cleanHttpsUrl(body?.mediaUrl);if(!['image','video'].includes(mediaType)||!url)return json({error:'Valid https image/video URL required'},400);const {data,error}=await admin.from('mission365_mission_media').insert({profile_id:profileId,media_type:mediaType,media_url:url,alt_text:String(body?.altText||'').slice(0,500),caption:String(body?.caption||'').slice(0,2000),is_featured:body?.isFeatured===true,sort_order:Number(body?.sortOrder||0),source_status:'sourced',status:'published'}).select('*').single();if(error)throw error;if(body?.isFeatured===true)await admin.from('mission365_mission_profiles').update({cover_media_url:url,updated_at:new Date().toISOString()}).eq('id',profileId);return json({media:data})}
 if(action==='delete_media'){const id=String(body?.id||'');const {data:row}=await admin.from('mission365_mission_media').select('id').eq('id',id).eq('profile_id',profileId).maybeSingle();if(!row)return json({error:'Media not found'},404);const {error}=await admin.from('mission365_mission_media').delete().eq('id',id);if(error)throw error;return json({deleted:true})}
 if(action==='add_post'){const title=String(body?.title||'').trim(),postBody=String(body?.body||'').trim(),postType=String(body?.postType||'update'),rawMedia=String(body?.mediaUrl||'').trim(),mediaUrl=cleanHttpsUrl(rawMedia);if(title.length<2||postBody.length<5||!['update','story','event','press','impact'].includes(postType))return json({error:'Post title, body, and valid type are required'},400);if(rawMedia&&!mediaUrl)return json({error:'Post media must be a valid https URL'},400);const {data,error}=await admin.from('mission365_mission_posts').insert({profile_id:profileId,title,body:postBody,post_type:postType,media_url:mediaUrl,status:'published',published_at:new Date().toISOString()}).select('*').single();if(error)throw error;return json({post:data})}
 if(action==='add_testimonial'){const author=String(body?.authorName||'').trim(),quote=String(body?.quote||'').trim(),rawPhoto=String(body?.photoUrl||'').trim(),rawSource=String(body?.sourceUrl||'').trim(),photoUrl=cleanHttpsUrl(rawPhoto),sourceUrl=cleanHttpsUrl(rawSource);if(author.length<2||quote.length<5)return json({error:'Testimonial author and quote are required'},400);if(rawPhoto&&!photoUrl)return json({error:'Testimonial photo must be a valid https URL'},400);if(rawSource&&!sourceUrl)return json({error:'Testimonial source must be a valid https URL'},400);const {data,error}=await admin.from('mission365_mission_testimonials').insert({profile_id:profileId,author_name:author,author_role:String(body?.authorRole||'').trim(),quote,photo_url:photoUrl,source_url:sourceUrl,verification_status:'pending',status:'draft'}).select('*').single();if(error)throw error;return json({testimonial:data,message:'Testimonial submitted for verification before public display.'})}
 if(action==='add_testimonial_request'){const targetRole=String(body?.targetRole||'').trim();if(targetRole.length<2)return json({error:'Testimonial source role is required'},400);const {data,error}=await admin.from('mission365_testimonial_requests').insert({profile_id:profileId,target_role:targetRole,target_name:String(body?.targetName||'').trim()||null,contact_reference:String(body?.contactReference||'').trim()||null,request_status:'queued',consent_status:'pending',anonymity_allowed:body?.anonymityAllowed===true,notes:String(body?.notes||'').trim()}).select('*').single();if(error)throw error;return json({testimonialRequest:data})}
 if(action==='update_testimonial_request'){const id=String(body?.id||'');const {data:existing}=await admin.from('mission365_testimonial_requests').select('id').eq('id',id).eq('profile_id',profileId).maybeSingle();if(!existing)return json({error:'Testimonial request not found'},404);const patch:any={updated_at:new Date().toISOString()};if(body?.requestStatus!==undefined){const v=String(body.requestStatus);if(!['queued','sent','responded','declined','verified'].includes(v))return json({error:'Invalid request status'},400);patch.request_status=v}if(body?.consentStatus!==undefined){const v=String(body.consentStatus);if(!['pending','granted','declined','not_required'].includes(v))return json({error:'Invalid consent status'},400);patch.consent_status=v}for(const [bodyKey,dbKey] of [['targetName','target_name'],['contactReference','contact_reference'],['evidenceReference','evidence_reference'],['notes','notes']] as const)if(body?.[bodyKey]!==undefined)patch[dbKey]=String(body[bodyKey]||'').trim()||null;const {data,error}=await admin.from('mission365_testimonial_requests').update(patch).eq('id',id).select('*').single();if(error)throw error;return json({testimonialRequest:data})}
 if(action==='add_opportunity'){const title=String(body?.title||'').trim(),spotsRaw=body?.spotsTotal,spots=spotsRaw===null||spotsRaw===undefined||spotsRaw===''?null:Number(spotsRaw);if(title.length<2)return json({error:'Opportunity title is required'},400);if(spots!==null&&(!Number.isInteger(spots)||spots<1))return json({error:'Volunteer spots must be a positive whole number'},400);const startsAt=body?.startsAt||null,endsAt=body?.endsAt||null;if(startsAt&&Number.isNaN(Date.parse(String(startsAt))))return json({error:'Invalid opportunity start time'},400);if(endsAt&&Number.isNaN(Date.parse(String(endsAt))))return json({error:'Invalid opportunity end time'},400);if(startsAt&&endsAt&&Date.parse(String(endsAt))<=Date.parse(String(startsAt)))return json({error:'Opportunity end time must be after its start time'},400);const {data,error}=await admin.from('mission365_volunteer_opportunities').insert({profile_id:profileId,title,description:String(body?.description||'').trim(),location:String(body?.location||'').trim()||null,starts_at:startsAt,ends_at:endsAt,spots_total:spots,status:'open'}).select('*').single();if(error)throw error;return json({opportunity:data})}
 if(action==='close_opportunity'){const id=String(body?.id||'');const {data,error}=await admin.from('mission365_volunteer_opportunities').update({status:'closed',updated_at:new Date().toISOString()}).eq('id',id).eq('profile_id',profileId).select('*').single();if(error)throw error;return json({opportunity:data})}
 return json({error:'Unsupported action'},400)}catch(error){console.error('mission365 profile manager failed',error);return json({error:error instanceof Error?error.message:'Profile operation failed'},500)}})
