import { createClient } from 'npm:@supabase/supabase-js@2.112.0'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>Response.json(body,{status,headers:{...cors,'cache-control':'no-store'}})
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_ANON_KEY')!}
function secretKey(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');return modern?JSON.parse(modern).default:Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!}
function admin(){return createClient(Deno.env.get('SUPABASE_URL')!,secretKey(),{auth:{persistSession:false,autoRefreshToken:false}})}
function scoped(auth:string){return createClient(Deno.env.get('SUPABASE_URL')!,publicKey(),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
async function stripeSecret(db:any){let key=Deno.env.get('STRIPE_SECRET_KEY')||'';if(!key){const {data}=await db.rpc('mission365_get_runtime_secret',{secret_name:'stripe_api_key'});key=String(data||'')}return key}
async function memberRole(db:any,userId:string,organizationId:string){const {data}=await db.from('mission365_organization_members').select('member_role').eq('user_id',userId).eq('organization_id',organizationId).maybeSingle();return data?.member_role||null}
async function requireUser(req:Request){const auth=req.headers.get('authorization')||'';const token=auth.startsWith('Bearer ')?auth.slice(7):'';if(!token)return {error:json({error:'Authentication required'},401)};const {data:{user},error}=await scoped(auth).auth.getUser(token);if(error||!user)return {error:json({error:'Invalid session'},401)};return {user}}
function transferStatus(account:any){return String(account?.configuration?.recipient?.capabilities?.stripe_balance?.stripe_transfers?.status||'inactive')}
function requirements(account:any){const reqs=account?.requirements;return reqs?.entries||reqs?.currently_due||reqs||[]}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const authResult=await requireUser(req);if('error' in authResult)return authResult.error;const user=authResult.user!;const db=admin();const body=await req.json();const action=String(body?.action||'');const organizationId=String(body?.organizationId||'');if(!organizationId)return json({error:'organizationId is required'},400);const role=await memberRole(db,user.id,organizationId);if(!['owner','manager'].includes(role||''))return json({error:'Organization owner or manager access required'},403);const {data:org}=await db.from('mission365_organizations').select('id,legal_name,public_name,organization_type,verification_status').eq('id',organizationId).maybeSingle();if(!org)return json({error:'Organization not found'},404);const key=await stripeSecret(db);if(!key||key.startsWith('REPLACE_WITH_'))return json({error:'Stripe Connect is credential-gated until the Mission 365 restricted API key is installed.'},503)
if(action==='create_account'){if(org.verification_status!=='verified')return json({error:'Connected account creation is locked until Mission 365 verification is complete.'},409);const {count:accepted}=await db.from('mission365_documents').select('id',{count:'exact',head:true}).eq('organization_id',organizationId).eq('review_status','accepted');if(!accepted)return json({error:'Connected account creation is locked until verification evidence is accepted.'},409);const {data:existing}=await db.from('mission365_payout_accounts').select('*').eq('organization_id',organizationId).maybeSingle();if(existing?.stripe_account_id)return json({account:existing,existing:true});if(!user.email)return json({error:'A confirmed contact email is required for Stripe onboarding.'},409);const payload={contact_email:user.email,display_name:org.public_name,defaults:{responsibilities:{fees_collector:'application',losses_collector:'application'}},dashboard:'express',identity:{country:'us',business_details:{registered_name:org.legal_name}},configuration:{recipient:{capabilities:{stripe_balance:{stripe_transfers:{requested:true}}}}},include:['configuration.recipient','identity','requirements']};const response=await fetch('https://api.stripe.com/v2/core/accounts',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.preview','Content-Type':'application/json','Idempotency-Key':`m365-connect-${organizationId}`},body:JSON.stringify(payload)});const account=await response.json();if(!response.ok)throw new Error(account?.error?.message||'Stripe connected account creation failed');const status=transferStatus(account);const {data:saved,error}=await db.from('mission365_payout_accounts').upsert({organization_id:organizationId,stripe_account_id:account.id,onboarding_status:status==='active'?'ready':'pending',transfers_status:status==='active'?'active':'restricted',requirements_due:requirements(account),last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:'organization_id'}).select('*').single();if(error)throw error;await db.from('mission365_audit_log').insert({actor_user_id:user.id,action:'connect.account.created',entity_type:'organization',entity_id:organizationId,after_state:{stripe_account_id:account.id,onboarding_status:saved.onboarding_status,transfers_status:saved.transfers_status},metadata:{dashboard:'express',configuration:'recipient'}});return json({account:saved,connectedAccountId:account.id})}
const {data:payout}=await db.from('mission365_payout_accounts').select('*').eq('organization_id',organizationId).maybeSingle();if(!payout?.stripe_account_id)return json({error:'No Stripe connected account exists for this organization.'},409)
if(action==='refresh'){const url=`https://api.stripe.com/v2/core/accounts/${encodeURIComponent(payout.stripe_account_id)}?include[]=configuration.recipient&include[]=identity&include[]=requirements`;const response=await fetch(url,{headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.preview'}});const account=await response.json();if(!response.ok)throw new Error(account?.error?.message||'Stripe account refresh failed');const status=transferStatus(account);const due=requirements(account);const onboarding=status==='active'?'ready':(Array.isArray(due)&&due.length?'requirements_due':'pending');const {data:saved,error}=await db.from('mission365_payout_accounts').update({onboarding_status:onboarding,transfers_status:status==='active'?'active':'restricted',requirements_due:due,last_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('organization_id',organizationId).select('*').single();if(error)throw error;return json({account:saved,stripe:{id:account.id,transferStatus:status,requirements:due}})}
if(action==='hosted_onboarding'){const params=new URLSearchParams();params.set('account',payout.stripe_account_id);params.set('refresh_url','https://mission-365.vercel.app/app/mission-owner?connect=refresh');params.set('return_url','https://mission-365.vercel.app/app/mission-owner?connect=return');params.set('type','account_onboarding');const response=await fetch('https://api.stripe.com/v1/account_links',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.dahlia','Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});const link=await response.json();if(!response.ok)throw new Error(link?.error?.message||'Stripe hosted onboarding link creation failed');return json({url:link.url,expiresAt:link.expires_at})}
if(action==='account_session'){const params=new URLSearchParams();params.set('account',payout.stripe_account_id);params.set('components[account_onboarding][enabled]','true');params.set('components[account_management][enabled]','true');params.set('components[notification_banner][enabled]','true');const response=await fetch('https://api.stripe.com/v1/account_sessions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.dahlia','Content-Type':'application/x-www-form-urlencoded'},body:params.toString()});const session=await response.json();if(!response.ok)throw new Error(session?.error?.message||'Stripe account session creation failed');return json({clientSecret:session.client_secret,accountId:payout.stripe_account_id})}
if(action==='express_login'){const response=await fetch(`https://api.stripe.com/v1/accounts/${encodeURIComponent(payout.stripe_account_id)}/login_links`,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Stripe-Version':'2026-06-24.dahlia','Content-Type':'application/x-www-form-urlencoded'}});const link=await response.json();if(!response.ok)throw new Error(link?.error?.message||'Express Dashboard link creation failed');return json({url:link.url})}return json({error:'Unsupported action'},400)}catch(error){console.error('mission365 connect failed',error);return json({error:error instanceof Error?error.message:'Connect request failed'},500)}})
